pluv-io/pluv

- packages/io/README.md
---
Fixed checkbox styles on the README for npm.
> chore: fixed checkbox styles on readme for npm

- .changeset/flat-icons-serve.md
- CONTRIBUTING.md
- packages/io/src/AbstractPersistance.ts
- packages/io/src/IORoom.ts
- packages/io/src/Persistance.ts
- packages/io/src/PluvIO.ts
- packages/persistance-redis/src/PersistanceRedis.ts
---
Support for room listeners to get storage states.
> feat(io): support for room listeners to get storage states

- packages/io/src/PluvIO.ts
- packages/io/src/createIO.ts
- packages/io/src/index.ts
---
Fixed not being able to set listeners on `createIO`.
> fix(io): fixed not being able to set listeners on createIO

- apps/server-node/package.json
- apps/web/package.json
- package.json
- packages/cli/package.json
- packages/crdt-yjs/package.json
- packages/eslint-config-pluv/package.json
- pnpm-lock.yaml
- tests/e2e/package.json
> chore: bumped dependencies

- .changeset/rich-carrots-return.md
---
Added changeset for bumped dependencies.
> chore: added changeset

- .changeset/brown-stingrays-design.md
- packages/crdt-yjs/README.md
- packages/io/README.md
> Updated readme links

- .changeset/modern-carrots-develop.md
- packages/io/README.md
> Add missing doc links

- .kodiak.toml
---
Added kodiak for keeping branches up to date.
> chore: added kodiak

- apps/server-node/package.json
- pnpm-lock.yaml
---
Uninstall unused `wrangler` dependency from @pluv-app/server-node.
> chore: uninstall unused wrangler from server-node

- .changeset/dull-bobcats-chew.md
- packages/cli/README.md
- packages/client/README.md
- packages/crdt-yjs/README.md
- packages/io/README.md
- packages/persistance-redis/README.md
- packages/platform-cloudflare/README.md
- packages/platform-node/README.md
- packages/pubsub-redis/README.md
- packages/react/README.md
---
Added disclaimer to the README, warning about breaking changes while the packages are in preview.
> docs: added disclaimer not to use packages in production while in preview

- packages/io/README.md
---
Added the openbase badge onto the README.
> chore: added openbase badge on readme

- packages/client/README.md
- packages/crdt-yjs/README.md
- packages/io/README.md
- packages/persistance-redis/README.md
- packages/platform-cloudflare/README.md
- packages/platform-node/README.md
- packages/pubsub-redis/README.md
- packages/react/README.md
---
Center aligned demo gif on READMEs.
> chore: center align demo gif on readme

- .changeset/hot-schools-clean.md
- apps/web/src/components/CloudflareChatRoom.tsx
- apps/web/src/components/NodeChatRoom.tsx
- docs/custom-events.md
- docs/react-api.md
- packages/client/src/PluvRoom.ts
- packages/io/README.md
- packages/react/README.md
- packages/react/src/createRoomBundle.tsx
---
**BREAKING:** Updated `PluvRoom.broadcast` api
Previous:
```ts
const broadcast = usePluvBroadcast();
broadcast({
type: "SEND_MESSAGE",
data: { message: "hello world" },
});
```
Current:
```ts
const broadcast = usePluvBroadcast();
broadcast("SEND_MESSAGE", { message: "hello world" });
```
> feat: breaking: updated PluvRoom broadcast api

- pnpm-lock.yaml
- tests/e2e/package.json
---
* Upgrade playwright version.
> chore: bump playwright

- .changeset/honest-pianos-agree.md
- packages/client/src/AbstractRoom.ts
- packages/client/src/MockedRoom.ts
- packages/client/src/PluvRoom.ts
- packages/client/src/index.ts
- packages/client/src/types.ts
---
* Added mocked room for testing client code.
> feat(client): added mocked room for testing client code

- .changeset/forty-vans-dance.md
- packages/react/src/createRoomBundle.tsx
---
* Added MockedRoomProvider out of `createRoomBundle`.
> feat(react): added MockedRoomProvider for testing on storybook

- apps/storybook/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/client/CHANGELOG.md
- packages/client/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
> fix: fixed broken release

- .changeset/dull-panthers-tickle.md
- apps/server-cloudflare/package.json
- apps/storybook/package.json
- apps/web/package.json
- internal/cloudflare-utils/package.json
- internal/rainfall/package.json
- internal/react-chess/package.json
- internal/react-hooks/package.json
- package.json
- packages/cli/package.json
- packages/client/package.json
- packages/crdt-yjs/package.json
- packages/eslint-config-pluv/package.json
- packages/io/package.json
- packages/persistance-redis/package.json
- packages/platform-cloudflare/package.json
- packages/platform-node/package.json
- packages/pubsub-redis/package.json
- packages/react/package.json
- packages/types/package.json
- pnpm-lock.yaml
- tests/e2e/package.json
> chore: bump deps

- apps/storybook/.storybook/preview-head.html
- apps/storybook/next-env.d.ts
- apps/storybook/package.json
- apps/storybook/public/tailwind.css
- apps/storybook/types.d.ts
- apps/web/package.json
- apps/web/src/components/HomeHero/HomeHero.tsx
- apps/web/src/pages/_app.tsx
- apps/web/src/pages/_document.tsx
- apps/web/src/pages/index.tsx
- apps/web/tsconfig.json
- apps/web/types.d.ts
- internal/react-components/src/atoms/PageContainer/PageContainer.tsx
- internal/react-components/src/atoms/PageContainer/index.ts
- internal/react-components/src/atoms/index.ts
- internal/react-components/src/index.ts
- internal/react-components/src/molecules/Typist/TypistCursor.tsx
- internal/react-components/src/molecules/Typist/index.ts
- internal/react-components/src/molecules/index.ts
- internal/react-components/tsconfig.json
- internal/react-components/types.d.ts
- internal/tailwind-config/tailwind.config.js
- internal/typings/.eslintrc.js
- internal/typings/package.json
- internal/typings/src/index.d.ts
- internal/typings/src/twin.d.ts
- internal/typings/src/ui.d.ts
- internal/typings/tsconfig.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
---
Completed first iteration of home-hero.
> feat: home hero

- apps/storybook/package.json
- apps/storybook/public/tailwind.css
- apps/storybook/src/react-chess/ChessBoard.stories.tsx
- apps/web/src/components/HomeChessDemo/HomeChessDemo.tsx
- apps/web/src/components/HomeIntroSection/HomeIntroSection.tsx
- internal/react-chess/src/ChessBoard.tsx
- internal/react-chess/src/ChessMoveHistory.tsx
- pnpm-lock.yaml
---
Styled chess board for demo.
> feat: styled chess board

- apps/storybook/public/tailwind.css
- apps/web/src/components/HomeChessDemo/useOtherSquares.ts
- apps/web/src/pages/index.tsx
- apps/web/src/pluv-io/cloudflare.ts
- internal/react-chess/src/ChessBoard.tsx
---
Added progress chess presence. This is blocked until `react-chessboard` supports a custom square renderer.
> feat: added progress for chess presence

- apps/storybook/public/tailwind.css
- apps/storybook/src/react-code/MultiPrismCode.stories.tsx
- internal/react-code/package.json
- internal/react-code/src/LaserWaveTheme.tsx
- internal/react-code/src/MultiPrismCode.tsx
- internal/react-code/src/PrismCode.tsx
- internal/react-code/src/index.ts
- pnpm-lock.yaml
---
Added MultiPrismCode to `react-code`.
> feat(react-code): added MultiPrismCode

- .changeset/grumpy-otters-beam.md
- apps/storybook/src/web/components/HomeChessDemo.stories.tsx
- apps/storybook/src/web/pages/index.stories.tsx
- apps/web/src/components/HomeCodeDemo/HomeCodeDemo.tsx
- apps/web/src/pluv-io/cloudflare.ts
- docs/crdt-storage.md
- docs/react-api.md
- packages/cli/template/base/src/components/ChatRoom.tsx
- packages/cli/template/base/src/pluv-io.ts
- packages/client/src/y.ts
- packages/crdt-yjs/src/index.ts
- packages/crdt-yjs/src/object.ts
- packages/react/README.md
- tests/e2e/src/components/CloudflareStorageRoom.tsx
- tests/e2e/src/components/NodeRedisStorageRoom.tsx
- tests/e2e/src/components/NodeStorageRoom.tsx
- tests/e2e/src/pluv-io/cloudflare.ts
- tests/e2e/src/pluv-io/node-redis.ts
- tests/e2e/src/pluv-io/node.ts
---
Renamed y.unstable__object to y.object
> feat: renamed y.unstable__object to y.object

- .github/workflows/e2e-tests.yml
- apps/server-cloudflare/package.json
- docker-compose.yml
- pnpm-lock.yaml
- tests/e2e/package.json
- tests/e2e/src/server/node-redis/cluster.ts
> chore: updated playwright

- apps/storybook/public/tailwind.css
- apps/storybook/src/web/components/HomeBoxesDemoSection.stories.tsx
- apps/web/src/components/HomeBoxesDemoSection/HomeBoxesDemoSection.tsx
- apps/web/src/components/HomeBoxesDemoSection/index.ts
- apps/web/src/components/HomeCodeDemo/HomeCodeDemo.tsx
- apps/web/src/components/index.ts
- apps/web/src/pages/index.tsx
- internal/react-code/src/MultiPrismCode.tsx
---
Integrated code demo to home page.
> feat: integrated code demo to home page

- apps/storybook/public/tailwind.css
- apps/web/src/components/HomeCodeDemo/HomeCodeDemo.tsx
- apps/web/src/components/HomeCodeDemo/HomeCodeDemoBrowser.tsx
- apps/web/src/components/HomeCodeDemo/constants.ts
---
Added user name to code demo.
> feat: added user name to code demo

- apps/storybook/public/tailwind.css
- apps/storybook/src/web/components/HomeFeaturesSection.stories.tsx
- apps/web/src/components/HomeCodeDemo/HomeCodeDemo.tsx
- apps/web/src/components/HomeFeaturesSection/HomeFeaturesSection.tsx
- apps/web/src/components/HomeFeaturesSection/HomeFeaturesSectionFeature.tsx
- apps/web/src/components/HomeFeaturesSection/index.ts
- apps/web/src/components/index.ts
- apps/web/src/pages/index.tsx
---
Added features section to home page.
> feat: added features section to home page

- apps/storybook/public/tailwind.css
- apps/storybook/src/web/components/HomeTypeSafetyDemo.stories.tsx
- apps/web/package.json
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemo.tsx
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoClient.tsx
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoServer.tsx
- apps/web/src/components/HomeTypeSafetyDemo/index.ts
- apps/web/src/components/index.ts
- internal/react-code/src/PrismCode.tsx
- internal/react-components/src/molecules/Typist/Typist.tsx
- internal/react-hooks/package.json
- internal/react-hooks/src/index.ts
- internal/react-hooks/src/useOrchestratedTypist.ts
- internal/react-hooks/src/useTypist.ts
- pnpm-lock.yaml
- tests/e2e/src/server/node/pluv-io.ts
---
Added code-writing for server-code in the home-page's type-safety demo component.
> chore: added code writing for server code in type-safety demo

- apps/storybook/public/tailwind.css
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemo.tsx
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoServerToken.tsx
- internal/react-code/src/CodeTooltip.tsx
- internal/react-hooks/src/index.ts
- internal/react-hooks/src/useOrchestratedTypist.ts
- internal/react-hooks/src/useTypist.ts
---
Added reset method to orchestrated typist.
> refactor: added orchestrated reset

- apps/storybook/public/tailwind.css
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemo.tsx
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoClient.tsx
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoClientToken.tsx
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoServer.tsx
---
Added message tooltip to client snippet.
> feat: added message tooltip to client snippet

- apps/storybook/public/tailwind.css
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemo.tsx
- internal/react-code/src/CodeTooltip.tsx
---
Added responsiveness to type-safety demo.
> feat: added responsive type-safety demo

- apps/storybook/.storybook/preview.tsx
- apps/storybook/public/tailwind.css
- apps/storybook/src/web/components/HomeCodeDemo.stories.tsx
- apps/web/src/components/HomeCodeDemo/HomeCodeDemo.tsx
- apps/web/src/components/HomeCodeDemo/HomeCodeDemoBox.tsx
- apps/web/src/components/HomeCodeDemo/HomeCodeDemoBrowser.tsx
- apps/web/src/components/HomeCodeDemo/HomeCodeDemoUserDemo.tsx
- apps/web/src/components/HomeCodeDemo/constants.ts
- apps/web/src/components/HomeCodeDemo/context.ts
- internal/react-code/src/MultiPrismCode.tsx
- internal/react-hooks/src/index.ts
- internal/react-hooks/src/useMediaQuery.ts
---
Added responsive code demo.
> feat: added responsive code demo

- apps/storybook/public/tailwind.css
- apps/storybook/src/web/components/HomeTypeSafetyDemoSection.stories.tsx
- apps/web/src/components/HomeBoxesDemoSection/HomeBoxesDemoSection.tsx
- apps/web/src/components/HomeFeaturesSection/HomeFeaturesSection.tsx
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemo.tsx
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoServerToken.tsx
- apps/web/src/components/HomeTypeSafetyDemoSection/HomeTypeSafetyDemoSection.tsx
- apps/web/src/components/HomeTypeSafetyDemoSection/index.ts
- apps/web/src/components/index.ts
- apps/web/src/pages/index.tsx
- internal/react-hooks/src/useTypist.ts
---
Integrated type-safety demo to home page.
> feat: integrated type-safety demo

- apps/web/src/components/HomeChessDemo/HomeChessDemo.tsx
- apps/web/src/components/HomeCodeDemo/HomeCodeDemoBrowser.tsx
- apps/web/src/pages/_app.tsx
- apps/web/src/pluv-io/cloudflare.ts
- internal/react-chess/src/ChessBoard.tsx
- internal/react-chess/src/index.ts
---
Fixed home page render issues.
> fix: fix home page render issues

- apps/storybook/src/react-chess/LoadingChessBoard.stories.tsx
- apps/web/src/components/HomeChessDemo/HomeChessDemo.tsx
- internal/react-chess/src/LoadingChessBoard.tsx
- internal/react-chess/src/index.ts
---
Added LoadingChessBoard to home page demo.
> feat: added loading chess-board

- apps/storybook/.storybook/preview.js
- internal/react-chess/package.json
- internal/react-chess/src/KingPiece.tsx
- internal/react-chess/src/LoadingChessBoard.tsx
- internal/react-chess/src/index.ts
- internal/tailwind-config/tailwind.config.js
- internal/typings/src/twin.d.ts
- pnpm-lock.yaml
---
Integrated loading chess board.
> feat: integrated loading chess board

- apps/storybook/package.json
- apps/web/package.json
- pnpm-lock.yaml
---
Added missing babel-plugin-styled-components
> chore: added missing babel-plugin-styled-components

- apps/storybook/src/react-components/atoms/Footer.stories.tsx
- apps/storybook/src/web/components/SiteWideFooter.stories.tsx
- apps/web/src/components/SiteWideFooter/SiteWideFooter.tsx
- apps/web/src/components/SiteWideFooter/index.ts
- apps/web/src/components/index.ts
- internal/react-components/src/atoms/AppBar/AppBar.tsx
- internal/react-components/src/atoms/Footer/Footer.tsx
- internal/react-components/src/atoms/Footer/index.ts
- internal/react-components/src/atoms/index.ts
> feat: added site-wide-footer

- apps/storybook/src/web/components/SiteWideLayout.stories.tsx
- apps/storybook/src/web/pages/index.stories.tsx
- apps/web/src/components/SiteWideLayout/SiteWideLayout.tsx
- apps/web/src/components/SiteWideLayout/index.ts
- apps/web/src/components/index.ts
- apps/web/src/pages/_app.tsx
- internal/react-components/src/atoms/Footer/Footer.tsx
> feat: added site-wide-layout

- internal/react-components/src/z-indices.ts
> fix: fix z-indices

- apps/storybook/src/web/pages/index.stories.tsx
- apps/web/src/pages/_app.tsx
- apps/web/src/pages/index.tsx
> fix: fix home-page padding

- apps/storybook/src/react-components/atoms/SideBar.stories.tsx
- apps/storybook/src/react-components/atoms/SideDrawer.stories.tsx
- apps/web/src/pages/_app.tsx
- internal/react-components/package.json
- internal/react-components/src/atoms/AppBar/AppBar.tsx
- internal/react-components/src/atoms/LazyMotion/LazyMotion.tsx
- internal/react-components/src/atoms/LazyMotion/features.ts
- internal/react-components/src/atoms/LazyMotion/index.ts
- internal/react-components/src/atoms/SideBar/SideBar.tsx
- internal/react-components/src/atoms/SideBar/index.ts
- internal/react-components/src/atoms/SideDrawer/SideDrawer.tsx
- internal/react-components/src/atoms/SideDrawer/SideDrawerRoot.tsx
- internal/react-components/src/atoms/SideDrawer/SideDrawerTrigger.tsx
- internal/react-components/src/atoms/SideDrawer/index.ts
- internal/react-components/src/atoms/VisuallyHidden/VisuallyHidden.tsx
- internal/react-components/src/atoms/VisuallyHidden/index.ts
- internal/react-components/src/atoms/index.ts
- internal/react-components/src/z-indices.ts
- pnpm-lock.yaml
---
Added SideBar and SideDrawer.
> feat: added side-bar

- apps/storybook/.storybook/preview.js
- apps/storybook/src/react-components/molecules/TreeView.stories.tsx
- internal/react-chess/package.json
- internal/react-components/package.json
- internal/react-components/src/molecules/TreeView/TreeView.tsx
- internal/react-components/src/molecules/TreeView/TreeViewButton.tsx
- internal/react-components/src/molecules/TreeView/TreeViewLink.tsx
- internal/react-components/src/molecules/TreeView/TreeViewList.tsx
- internal/react-components/src/molecules/TreeView/index.ts
- internal/react-icons/src/index.tsx
- internal/react-icons/svgs/ChevronDownIcon.svg
- internal/typings/src/twin.d.ts
- pnpm-lock.yaml
> feat: added tree-view

- apps/storybook/src/web/components/DocsLayout.stories.tsx
- apps/storybook/src/web/components/SiteWideLayout.stories.tsx
- apps/web/src/components/DocsLayout/DocsLayout.tsx
- apps/web/src/components/DocsLayout/DocsLayoutContent.tsx
- apps/web/src/components/DocsLayout/index.ts
- apps/web/src/components/SiteWideFooter/SiteWideFooter.tsx
- apps/web/src/components/SiteWideLayout/SiteWideLayout.tsx
- apps/web/src/components/SiteWideLayout/SiteWideLayoutContent.tsx
- apps/web/src/components/index.ts
- apps/web/src/pages/_app.tsx
- apps/web/src/pages/index.tsx
- internal/react-components/src/atoms/SideBar/SideBar.tsx
- internal/react-components/src/molecules/TreeView/TreeViewList.tsx
> feat: added docs layout

- apps/web/next.config.mjs
- apps/web/package.json
- apps/web/src/pages/docs/index.mdx
- pnpm-lock.yaml
> feat: added initial docs page

- .changeset/fifty-parents-camp.md
- packages/cli/README.md
- packages/client/README.md
- packages/crdt-yjs/README.md
- packages/io/README.md
- packages/persistance-redis/README.md
- packages/platform-cloudflare/README.md
- packages/platform-node/README.md
- packages/pubsub-redis/README.md
- packages/react/README.md
---
Fixed links to other pluv packages in readmes.
> fix: fixed readme links

- apps/web/src/components/DocsLayout/DocsLayout.tsx
---
Fix bounded content area for docs layout.
> feat: fix bounding area for docs layout

- apps/storybook/package.json
- apps/storybook/src/react-components/atoms/Anchor.stories.tsx
- apps/storybook/src/react-components/molecules/TableOfContents.stories.tsx
- apps/storybook/src/react-components/molecules/TreeView.stories.tsx
- internal/react-components/src/atoms/Anchor/Anchor.tsx
- internal/react-components/src/atoms/Anchor/index.ts
- internal/react-components/src/atoms/index.ts
- internal/react-components/src/molecules/TableOfContents/TableOfContents.tsx
- internal/react-components/src/molecules/TableOfContents/index.ts
- internal/react-components/src/molecules/TreeView/TreeViewButton.tsx
- internal/react-components/src/molecules/TreeView/TreeViewLink.tsx
- internal/react-components/src/molecules/TreeView/TreeViewList.tsx
- internal/react-components/src/molecules/index.ts
- pnpm-lock.yaml
> feat: added table-of-contents

- apps/storybook/.storybook/main.js
- apps/storybook/.storybook/preview.js
- apps/storybook/package.json
- apps/storybook/src/web/components/DocsLayout.stories.tsx
- apps/web/package.json
- apps/web/src/components/DocsLayout/DocsLayout.tsx
- apps/web/src/components/SiteWideAppBar/SiteWideAppBar.tsx
- apps/web/src/components/SiteWideLayout/SiteWideLayout.tsx
- internal/mdx-components/package.json
- internal/react-chess/package.json
- internal/react-code/package.json
- internal/react-components/package.json
- internal/react-components/src/atoms/PageContainer/PageContainer.tsx
- internal/react-components/src/atoms/SideBar/SideBar.tsx
- internal/react-components/src/molecules/TableOfContents/TableOfContents.tsx
- internal/typings/package.json
- pnpm-lock.yaml
---
* Integrated TableOfContents into DocsLayout.
* Fixed importing multiple styled-components.
> feat: integrate table-of-contents

- apps/storybook/src/react-components/atoms/Pill.stories.tsx
- apps/storybook/src/react-components/molecules/Breadcrumbs.stories.tsx
- apps/storybook/src/react-components/molecules/TableOfContents.stories.tsx
- internal/react-components/src/atoms/Pill/Pill.tsx
- internal/react-components/src/atoms/Pill/index.ts
- internal/react-components/src/atoms/index.ts
- internal/react-components/src/molecules/Breadcrumbs/Breadcrumbs.tsx
- internal/react-components/src/molecules/Breadcrumbs/BreadcrumbsItem.tsx
- internal/react-components/src/molecules/Breadcrumbs/index.ts
- internal/react-components/src/molecules/index.ts
> feat: added breadcrumbs

- apps/web/src/components/DocsLayout/DocsLayout.tsx
---
Fixed TableOfContents not refreshing contents on route changes.
> fix: fixed toc contents between pages

- .changeset/few-icons-arrive.md
- apps/server-cloudflare/package.json
- apps/storybook/package.json
- apps/web/package.json
- internal/cloudflare-utils/package.json
- internal/mdx-components/package.json
- internal/rainfall/package.json
- internal/react-chess/package.json
- internal/react-code/package.json
- internal/react-components/package.json
- internal/react-hooks/package.json
- internal/react-icons/package.json
- internal/typings/package.json
- packages/cli/package.json
- packages/client/package.json
- packages/crdt-yjs/package.json
- packages/eslint-config-pluv/package.json
- packages/io/package.json
- packages/persistance-redis/package.json
- packages/platform-cloudflare/package.json
- packages/platform-node/package.json
- packages/pubsub-redis/package.json
- packages/react/package.json
- packages/types/package.json
- pnpm-lock.yaml
- tests/e2e/package.json
---
Updated TypeScript to 5.0.
> chore: upgrade typescript 5.0

- apps/storybook/package.json
- apps/web/scripts/generate-docs.ts
- apps/web/src/components/DocsTreeViewNavigation/DocsTreeViewNavigation.tsx
- apps/web/src/components/DocsTreeViewNavigation/DocsTreeViewNavigationRoutes.tsx
- apps/web/src/types.ts
- pnpm-lock.yaml
---
Integrated generated doc routes
> feat: integrated generate doc routes

- apps/storybook/.storybook/main.js
- apps/storybook/.storybook/preview.js
- apps/storybook/package.json
- apps/web/src/components/DocsLayout/DocsLayout.tsx
- pnpm-lock.yaml
---
Added missing next.js router addon.
> fix: fixed missing nextjs router storybook addon

- apps/storybook/src/web/components/DocsBreadcrumbs.stories.tsx
- apps/storybook/src/web/components/DocsLayout.stories.tsx
- apps/storybook/tsconfig.json
- apps/web/package.json
- apps/web/scripts/generate-docs.ts
- apps/web/src/components/DocsBreadcrumbs/DocsBreadcrumbs.tsx
- apps/web/src/components/DocsBreadcrumbs/index.ts
- apps/web/src/components/DocsLayout/DocsLayout.tsx
- apps/web/src/components/index.ts
- apps/web/tsconfig.json
- internal/react-components/src/atoms/Pill/Pill.tsx
- internal/react-components/src/molecules/Breadcrumbs/BreadcrumbsItem.tsx
- internal/utils/.eslintrc.js
- internal/utils/package.json
- internal/utils/src/get.ts
- internal/utils/src/index.ts
- internal/utils/tsconfig.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
> feat: added docs breadcrumbs

- apps/web/package.json
- apps/web/src/components/DocsLayout/DocsLayout.tsx
- apps/web/src/components/DocsTreeViewNavigation/DocsTreeViewNavigation.tsx
- apps/web/src/pages/_app.tsx
- internal/mdx-components/package.json
- internal/mdx-components/src/MdxHeader.tsx
- internal/mdx-components/src/index.ts
- pnpm-lock.yaml
> fix: fixed docs hydration

- apps/web/next.config.mjs
- apps/web/src/components/DocsLayout/DocsLayout.tsx
- internal/mdx-components/src/MdxHeader.tsx
- internal/react-components/src/molecules/TableOfContents/TableOfContents.tsx
---
Fixed missing mdx provider import source.
> fix: fix missing mdx config

- apps/web/package.json
- apps/web/src/components/DocsLayout/DocsLayout.tsx
- apps/web/src/inputs/docs/Introduction.mdx
- internal/mdx-components/src/MdxH1.tsx
- internal/mdx-components/src/MdxH2.tsx
- internal/mdx-components/src/MdxH3.tsx
- internal/mdx-components/src/MdxH4.tsx
- internal/mdx-components/src/MdxH5.tsx
- internal/mdx-components/src/MdxHeader.tsx
- internal/mdx-components/src/MdxLi.tsx
- internal/mdx-components/src/MdxUl.tsx
- internal/react-components/src/GlobalStyles.tsx
- internal/react-components/src/atoms/Anchor/Anchor.tsx
- internal/react-components/src/molecules/TableOfContents/TableOfContents.tsx
- pnpm-lock.yaml
---
* Added introduction docs page.
* Updated header and list styles.
* Updated script to watch doc source changes while in dev mode.
> feat: added introduction

- internal/mdx-components/src/MdxHeader.tsx
---
Fixed link header responsiveness.
> fix: fix link icon responsiveness

- internal/react-components/src/atoms/Seo/Seo.tsx
- internal/react-components/src/atoms/Seo/SeoDescription.tsx
- internal/react-components/src/atoms/Seo/SeoImage.tsx
- internal/react-components/src/atoms/Seo/SeoMisc.tsx
- internal/react-components/src/atoms/Seo/SeoTitle.tsx
- internal/react-components/src/atoms/Seo/index.ts
- internal/react-components/src/atoms/index.ts
- turbo.json
> feat: added seo component

- apps/web/src/components/DocsLayout/DocsLayout.tsx
- apps/web/src/components/DocsSeo/DocsSeo.tsx
- apps/web/src/components/DocsSeo/index.ts
- apps/web/src/components/index.ts
- apps/web/src/inputs/docs/Introduction.mdx
- internal/react-components/src/atoms/Seo/Seo.tsx
- internal/react-components/src/atoms/Seo/SeoTitle.tsx
> feat: added docs seo

- apps/web/src/inputs/docs/Quickstart.mdx
- apps/web/src/inputs/docs/io/Define Events.mdx
> feat: added define-events docs

- apps/web/src/components/SiteWideAppBar/SiteWideAppBar.tsx
- internal/react-chess/src/KingPiece.tsx
- internal/react-components/src/atoms/Anchor/Anchor.tsx
- internal/react-components/src/atoms/Button/Button.tsx
- pnpm-lock.yaml
- tests/e2e/package.json
---
Added links to docs in app bar.
> feat: added links to docs in app bar

- apps/web/src/inputs/docs/Quickstart.mdx
- apps/web/src/inputs/docs/io/Cloudflare Workers.mdx
- docs/cloudflare-support.md
- internal/mdx-components/src/MdxHeader.tsx
- internal/mdx-components/src/MdxP.tsx
- internal/mdx-components/src/MdxPre.tsx
---
Added Cloudflare Workers docs.
> feat: added cloudflare-workers docs

- apps/web/src/inputs/docs/io/Storage State.mdx
> feat: added storage-state docs

- apps/web/scripts/generate-docs.ts
- apps/web/src/components/DocsBreadcrumbs/DocsBreadcrumbs.tsx
- apps/web/src/inputs/docs/io/Loading Storage.mdx
- apps/web/src/inputs/docs/io/Node.js.mdx
- apps/web/src/pages/docs/[[...slug]].tsx
> feat: added node.js docs

- apps/web/src/inputs/docs/Quickstart.mdx
- apps/web/src/inputs/docs/client/Create Client.mdx
- apps/web/src/inputs/docs/client/Create Rooms.mdx
- apps/web/src/inputs/docs/client/meta.json
- apps/web/src/inputs/docs/io/Authorization.mdx
> feat: added create-client docs

- apps/web/src/components/DocsLayout/DocsLayout.tsx
- apps/web/src/components/DocsTreeViewNavigation/DocsTreeViewNavigationRoutes.tsx
- apps/web/src/inputs/docs/client/API Reference.mdx
- internal/mdx-components/src/MdxBlockQuote.tsx
- internal/mdx-components/src/MdxHeader.tsx
- internal/react-components/src/atoms/Seo/SeoMisc.tsx
> feat: added api reference docs

- apps/web/src/inputs/docs/client/API Reference.mdx
---
Updated the client api  reference docs to add missing `getStorage` docs.
> docs: updated client api reference docs to add missing getStorage

- .changeset/brown-zebras-sort.md
- .changeset/flat-ducks-brake.md
- apps/web/src/components/DocsTreeViewNavigation/DocsTreeViewNavigation.tsx
- apps/web/src/components/DocsTreeViewNavigation/DocsTreeViewNavigationRoutes.tsx
- apps/web/src/inputs/docs/client/API Reference.mdx
- apps/web/src/inputs/docs/io/API Reference.mdx
- internal/mdx-components/src/MdxTable.tsx
- packages/io/src/IORoom.ts
---
* Renamed `IORoom.room` to `IORoom.id`.
* Updated `IORoom.broadcast` to the same function signature as `PluvClient.broadcast`.
* Added `io` API Reference docs.
> feat: io api updates

- apps/web/src/inputs/docs/io/API Reference.mdx
---
Add missing createIO configs in docs.
> docs: add missing createIO configs

- apps/web/src/inputs/docs/Quickstart.mdx
- apps/web/src/inputs/docs/react/Create Bundle.mdx
- apps/web/src/inputs/docs/react/meta.json
- internal/mdx-components/package.json
- internal/mdx-components/src/MdxA.tsx
- internal/react-hooks/src/index.ts
- internal/react-hooks/src/useNoSsr.ts
- pnpm-lock.yaml
---
* Added Create Bundle docs.
* Fixed anchors not linking to external page.
* Fixed broken link to cloudflare-worker docs.
> docs: create bundle docs

- .changeset/polite-readers-retire.md
- apps/web/src/inputs/docs/Quickstart.mdx
- apps/web/src/inputs/docs/client/Create Client.mdx
- apps/web/src/inputs/docs/io/Define Events.mdx
- apps/web/src/inputs/docs/react/Custom Events.mdx
- internal/mdx-components/src/MdxHeader.tsx
> docs: custom events docs

- apps/web/src/inputs/docs/client/API Reference.mdx
- apps/web/src/inputs/docs/client/Create Rooms.mdx
- apps/web/src/inputs/docs/react/Create Bundle.mdx
- apps/web/src/inputs/docs/react/Create Rooms.mdx
---
Added react create-rooms docs.
> docs: added react create-rooms docs

- apps/web/src/components/DocsBreadcrumbs/DocsBreadcrumbs.tsx
- apps/web/src/inputs/docs/Quickstart.mdx
- apps/web/src/inputs/docs/react/Yjs Storage.mdx
> docs: add yjs storage docs

- apps/web/README.md
---
Update web package readme.
> docs: update web package readme

- apps/web/src/inputs/docs/react/Create Bundle.mdx
- apps/web/src/inputs/docs/react/Presence.mdx
- internal/react-components/src/molecules/TableOfContents/TableOfContents.tsx
---
Added react presence docs.
> docs: added react presence docs

- apps/web/src/components/DocsLayout/DocsLayout.tsx
- apps/web/src/inputs/docs/react/API Reference.mdx
- apps/web/src/inputs/docs/react/Yjs Storage.mdx
- internal/react-components/src/atoms/Button/Button.tsx
---
Added react API Reference docs.
> docs: react api reference docs

- package.json
---
* Fixed incorrect pnpm version in package.json.
* Removed unused husky script in package.json.
> refactor: clean-up incorrect scripts and versions

- packages/client/src/PluvRoom.ts
---
Remove old unintended code.
> refactor: remove old unintended code

- apps/storybook/package.json
- apps/storybook/src/react-chess/ChessBoard.stories.tsx
- apps/storybook/src/react-chess/LoadingChessBoard.stories.tsx
- apps/storybook/src/react-code/MultiPrismCode.stories.tsx
- apps/storybook/src/react-code/PrismCode.stories.tsx
- apps/storybook/src/react-components/molecules/Breadcrumbs.stories.tsx
- apps/storybook/src/react-components/molecules/TableOfContents.stories.tsx
- apps/storybook/src/react-components/molecules/TreeView.stories.tsx
- apps/storybook/src/react-components/molecules/Typist.stories.tsx
- apps/storybook/src/web/pages/index.stories.tsx
- apps/storybook/tsconfig.json
- pnpm-lock.yaml
---
Updated some stories to v3 CSF format.
> chore: update stories to v3 csf

- apps/storybook/src/react-chess/ChessBoard.stories.tsx
- apps/storybook/src/react-components/atoms/Anchor.stories.tsx
- apps/storybook/src/react-components/atoms/AppBar.stories.tsx
- apps/storybook/src/react-components/atoms/Button.stories.tsx
- apps/storybook/src/react-components/atoms/Footer.stories.tsx
- apps/storybook/src/react-components/atoms/LogoIcon.stories.tsx
- apps/storybook/src/react-components/atoms/PageContainer.stories.tsx
- apps/storybook/src/react-components/atoms/Paper.stories.tsx
- apps/storybook/src/react-components/atoms/Pill.stories.tsx
- apps/storybook/src/react-components/atoms/SideBar.stories.tsx
- apps/storybook/src/react-components/atoms/SideDrawer.stories.tsx
- apps/storybook/src/web/components/DocsBreadcrumbs.stories.tsx
- apps/storybook/src/web/components/DocsCard.stories.tsx
- apps/storybook/src/web/components/DocsLayout.stories.tsx
- apps/storybook/src/web/components/DocsTreeViewNavigation.stories.tsx
- apps/storybook/src/web/components/HomeBoxesDemoSection.stories.tsx
- apps/storybook/src/web/components/HomeChessDemo.stories.tsx
- apps/storybook/src/web/components/HomeCodeDemo.stories.tsx
- apps/storybook/src/web/components/HomeFeaturesSection.stories.tsx
- apps/storybook/src/web/components/HomeHero.stories.tsx
- apps/storybook/src/web/components/HomeTypeSafetyDemo.stories.tsx
- apps/storybook/src/web/components/HomeTypeSafetyDemoSection.stories.tsx
- apps/storybook/src/web/components/MobileDocsSideDrawer.stories.tsx
- apps/storybook/src/web/components/SiteWideAppBar.stories.tsx
- apps/storybook/src/web/components/SiteWideFooter.stories.tsx
- apps/storybook/src/web/components/SiteWideLayout.stories.tsx
---
Converted remaining stories to csf v3 format.
> chore: convert remaining stories to csf v3 format

- apps/storybook/package.json
- apps/storybook/src/react-components/atoms/Banner.stories.tsx
- apps/web/src/components/SiteWideLayout/SiteWideLayout.tsx
- internal/react-components/src/atoms/Banner/Banner.tsx
- internal/react-components/src/atoms/Banner/index.ts
- internal/react-components/src/atoms/index.ts
- internal/react-components/src/index.ts
> feat: added site-wide banner

- .github/workflows/build-checks.yml
---
Added build checks to for build and lint to workflows.
> ci: added build checks

- apps/server-cloudflare/package.json
- apps/server-cloudflare/wrangler-dev.toml
- apps/server-cloudflare/wrangler-prod.toml
- apps/web/.env
---
Added dev and server deploy scripts.
> chore: server deploy scripts

- apps/server-cloudflare/src/index.ts
- apps/server-cloudflare/src/typings.d.ts
- apps/server-cloudflare/wrangler-dev.toml
- apps/server-cloudflare/wrangler-prod.toml
- internal/cloudflare-utils/src/Router.ts
> feat: added server cors

- apps/server-cloudflare/src/index.ts
- apps/web/src/components/HomeChessDemo/HomeChessDemo.tsx
- internal/react-chess/src/ChessBoard.tsx
- internal/react-chess/src/index.ts
---
* Fixed not connectable websocket.
* Fixed not restarting chess game.
> fix: server fixes

- apps/web/src/inputs/docs/Quickstart.mdx
---
Fixed link to presence docs from quickstart docs.
> fix: fix link to presence from quickstart

- .changeset/mean-candles-switch.md
- packages/io/README.md
> docs: delete removed doc links

- apps/web/src/components/HomeHero/HomeHero.tsx
- internal/rainfall/src/DropletManager.ts
---
* Significantly reduced rainfall droplet count.
* Prevent loading rainfall on mobile.
> feat: reduce rainfall droplets

- apps/web/src/components/HomeHero/HomeHero.tsx
---
Update mobile hero gradient shape.
> feat: update mobile hero gradient shape

- apps/web/src/components/HomeFeaturesSection/HomeFeaturesSection.tsx
---
Updated home features descriptions.
> feat: update home features description

- .changeset/mean-pillows-turn.md
- apps/server-cloudflare/src/durable-objects/RoomDurableObject.ts
- apps/web/src/pages/index.tsx
- internal/rainfall/src/DropletAssets.ts
- internal/rainfall/src/Rainfall.ts
- packages/io/src/PluvIO.ts
- packages/io/src/index.ts
- turbo.json
---
Added debug option to `PluvIO.getRoom` (i.e. `PluvIO.getRoom("my-room", { debug: true })`.
> feat: added logging to development server

- .changeset/perfect-shrimps-burn.md
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
---
Purge empty rooms before joining room.
> feat: purge empty rooms before joining room

- .changeset/weak-panthers-kick.md
- .gitignore
- apps/server-cloudflare/package.json
- apps/web/.env
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
---
Fixed unresponsive yjs doc when last user leaves on cloudflare worker.
> fix: io room delete

- .changeset/rare-goats-exist.md
- .changeset/rich-balloons-work.md
- packages/client/package.json
- packages/client/src/MockedRoom.ts
- packages/client/src/PluvClient.ts
- packages/client/src/PluvRoom.ts
- packages/tsconfig/frontend-generic.json
- pnpm-lock.yaml
---
Fixed local yjs doc updates not applying while disconnected.
> fix: local crdt updates

- .changeset/stale-houses-sip.md
- packages/client/package.json
- packages/tsconfig/frontend-generic.json
- packages/tsconfig/library.json
- packages/tsconfig/react-library.json
- pnpm-lock.yaml
---
Updated tsconfigs back to es6 targets
> feat: es6 targets

- .changeset/eleven-ways-flow.md
- packages/client/src/AbstractRoom.ts
- packages/client/src/MockedRoom.ts
- packages/client/src/PluvRoom.ts
- packages/client/src/UsersManager.ts
- packages/react/src/createRoomBundle.tsx
- pnpm-lock.yaml
- tests/e2e/next.config.mjs
- tests/e2e/package.json
- tests/e2e/tsconfig.json
---
Updated PluvRoom and createRoomBundle to still update user's local presence while offline.
> feat: preserve my presence

- packages/io/src/IORoom.ts
---
Refactored IO websocket handlers.
> refactor: refactored io ws handlers

- apps/web/src/components/DocsLayout/DocsLayout.tsx
- apps/web/src/components/HomeFeaturesSection/HomeFeaturesSection.tsx
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoClient.tsx
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoClientToken.tsx
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoServer.tsx
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoServerToken.tsx
- internal/react-code/package.json
- internal/react-code/src/CodeTooltip.tsx
- internal/react-code/src/MultiPrismCode.tsx
- pnpm-lock.yaml
---
* Fixed documentation overflows on mobile.
* Fixed home code demo tabs shrinking.
* Fixed code tooltips showing on mobile.
> feat: ui fixes

- packages/client/src/PluvRoom.ts
---
Fixed reconnecting with heartbeats.
> fix: fixed reconnecting with heartbeat

- .changeset/mean-geese-fail.md
- packages/client/src/CrdtManager.ts
- packages/client/src/MockedRoom.ts
- packages/client/src/PluvRoom.ts
- packages/client/src/types.ts
- packages/crdt-yjs/src/doc.ts
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
- packages/types/src/pluv.ts
---
Sync storage when offline and reconneted.
> feat: sync storage when offline and reconnected

- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
---
Delete unused IORoom initialStorage.
> refactor: delete unused io room initialStorage

- apps/server-cloudflare/src/index.ts
- apps/web/src/inputs/docs/io/Cloudflare Workers.mdx
---
Added docs for createPluvHandler for @platform/cloudflare.
> docs: added docs for cloudflare createPluvHandler

- apps/web/src/inputs/docs/Quickstart.mdx
- apps/web/src/inputs/docs/io/Node.js.mdx
- apps/web/src/inputs/docs/react/API Reference.mdx
---
Updated quickstart to use createPluvHandler.
> docs: updated quickstart to use createPluvHandler

- apps/web/src/components/DocsLayout/DocsLayout.tsx
- apps/web/src/components/SiteWideAppBar/SiteWideAppBar.tsx
- apps/web/src/inputs/docs/Quickstart.mdx
- apps/web/src/inputs/docs/client/API Reference.mdx
- apps/web/src/inputs/docs/client/Create Client.mdx
- apps/web/src/inputs/docs/io/Authorization.mdx
- apps/web/src/inputs/docs/io/Loading Storage.mdx
- apps/web/src/inputs/docs/io/Node.js.mdx
---
* Fixed doc discrepencies.
* Fixed responsiveness issues.
> docs: fix doc discrepencies

- apps/web/src/components/DocsTreeViewNavigation/DocsTreeViewNavigation.tsx
- apps/web/src/components/DocsTreeViewNavigation/DocsTreeViewNavigationRoutes.tsx
- apps/web/src/components/MobileDocsSideDrawer/MobileDocsSideDrawer.tsx
- apps/web/src/components/SiteWideAppBar/SiteWideAppBar.tsx
- internal/react-components/src/molecules/TreeView/TreeViewLink.tsx
---
Close mobile menu when link is clicked.
> feat: close mobile menu on click link

- .changeset/big-ducks-play.md
- packages/client/src/AbstractRoom.ts
- packages/client/src/MockedRoom.ts
- packages/client/src/PluvRoom.ts
- packages/react/src/createRoomBundle.tsx
---
Changed current user's presence to be non-nullable.
> feat: non nullable user presence

- .changeset/fifty-olives-glow.md
- internal/tailwind-config/tailwind.config.js
- packages/io/src/AbstractPlatform.ts
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
- packages/io/src/createIO.ts
- packages/io/src/index.ts
- packages/io/src/types.ts
- packages/platform-cloudflare/src/CloudflarePlatform.ts
- packages/platform-cloudflare/src/createPluvHandler.ts
- packages/platform-cloudflare/src/platformCloudflare.ts
- packages/platform-node/src/NodePlatform.ts
- packages/platform-node/src/createPluvHandler.ts
- pnpm-lock.yaml
- tests/e2e/package.json
- tests/e2e/src/server/node-redis/index.ts
- tests/e2e/src/server/node/pluv-io.ts
---
Added platform-specific contexts to expose env in cloudflare and req in node.js in event listeners and resolvers.
> feat: platform contexts

- packages/cli/template/base/package.json
- packages/cli/template/base/src/pluv-io.ts
- packages/cli/template/base/src/server/index.ts
- packages/cli/template/base/src/server/pluv-io.ts
- pnpm-lock.yaml
> feat: update cli template

- .changeset/famous-turtles-smoke.md
> chore: add missing changeset

- apps/web/src/inputs/docs/io/API Reference.mdx
- apps/web/src/inputs/docs/io/Cloudflare Workers.mdx
- apps/web/src/inputs/docs/io/Loading Storage.mdx
> docs: updated api references

- apps/server-cloudflare/package.json
- apps/storybook/package.json
- apps/web/package.json
- internal/cloudflare-utils/package.json
- internal/mdx-components/package.json
- internal/rainfall/package.json
- internal/react-chess/package.json
- internal/react-code/package.json
- internal/react-components/package.json
- internal/react-hooks/package.json
- internal/react-icons/package.json
- internal/remark-plugins/package.json
- internal/tailwind-config/package.json
- internal/typings/package.json
- internal/utils/package.json
- packages/cli/package.json
- packages/client/package.json
- packages/crdt-yjs/package.json
- packages/eslint-config-pluv/package.json
- packages/io/package.json
- packages/persistance-redis/package.json
- packages/platform-cloudflare/package.json
- packages/platform-node/package.json
- packages/pubsub-redis/package.json
- packages/react/package.json
- packages/tsconfig/package.json
- packages/types/package.json
- pnpm-lock.yaml
- tests/e2e/package.json
> chore: upgrade react types

- apps/web/next.config.mjs
> feat: rewrite api to other site

- apps/storybook/package.json
- apps/web/package.json
- apps/web/src/components/HomeChessDemo/HomeChessDemo.tsx
- apps/web/tsconfig.json
- internal/mdx-components/package.json
- internal/react-chess/package.json
- internal/react-code/package.json
- internal/react-components/package.json
- internal/react-components/src/GlobalStyles.tsx
- internal/react-components/src/atoms/Anchor/Anchor.tsx
- internal/react-components/src/atoms/Button/Button.tsx
- internal/react-components/src/molecules/TreeView/TreeViewList.tsx
- internal/typings/package.json
- internal/typings/src/twin.d.ts
- pnpm-lock.yaml
---
Bump styled-components to latest.
> chore: bump styled-components

- .changeset/new-horses-matter.md
- apps/server-cloudflare/package.json
- apps/storybook/package.json
- apps/web/package.json
- internal/cloudflare-utils/package.json
- internal/mdx-components/package.json
- internal/rainfall/package.json
- internal/react-chess/package.json
- internal/react-code/package.json
- internal/react-components/package.json
- internal/react-hooks/package.json
- internal/react-icons/package.json
- internal/remark-plugins/package.json
- internal/tailwind-config/package.json
- internal/typings/package.json
- internal/utils/package.json
- packages/cli/package.json
- packages/client/package.json
- packages/crdt-yjs/package.json
- packages/eslint-config-pluv/package.json
- packages/io/package.json
- packages/persistance-redis/package.json
- packages/platform-cloudflare/package.json
- packages/platform-node/package.json
- packages/pubsub-redis/package.json
- packages/react/package.json
- packages/tsconfig/package.json
- packages/types/package.json
- pnpm-lock.yaml
---
Fix incorrectly including playwright dependency.
> fix: fix bad dependency

- .changeset/config.json
- .changeset/metal-kids-film.md
---
Update changeset to use a fixed versioning strategy. This is to ensure that packages use consistent dependencies.
> feat: update changeset to use fixed versioning strategy

- .changeset/config.json
---
Update versioning strategy to include all packages.
> chore: update versioning strategy

- packages/platform-node/src/NodePlatform.ts
---
Ordered imports for @pluv/platform-node.
> chore: order imports

- .changeset/funny-doors-pump.md
- packages/io/src/AbstractPlatform.ts
- packages/io/src/AbstractWebSocket.ts
- packages/io/src/IORoom.ts
- packages/platform-cloudflare/src/CloudflarePlatform.ts
- packages/platform-cloudflare/src/CloudflareWebSocket.ts
- packages/platform-node/src/NodePlatform.ts
- packages/platform-node/src/NodeWebSocket.ts
---
Passed through sessionId and userId to platform websocket.
> feat: add platform websocket inputs

- .changeset/nervous-points-pump.md
- packages/io/src/index.ts
---
Exposed type AbstractPlatformConfig type from @pluv/io.
> feat(io): expose abstract platform config type

- .changeset/config.json
---
Updated changeset config to be more explicit on fixed package patterns.
> chore: updated changeset config

- packages/io/src/IORoom.ts
---
Moved event parsing within try-catch.
> feat: move event parse in try-catch

- .changeset/fast-panthers-kneel.md
- packages/io/src/index.ts
---
Exported class `PluvIO` from `@pluv/io`.
> feat: export class from @pluv/io

- .changeset/sour-cups-bake.md
- packages/client/src/AbstractRoom.ts
- packages/client/src/AbstractStorageStore.ts
- packages/client/src/CrdtManager.ts
- packages/client/src/CrdtNotifier.ts
- packages/client/src/EventNotifier.ts
- packages/client/src/MockedRoom.ts
- packages/client/src/OtherNotifier.ts
- packages/client/src/PluvClient.ts
- packages/client/src/PluvRoom.ts
- packages/client/src/StateNotifier.ts
- packages/client/src/UsersManager.ts
- packages/client/src/createClient.ts
- packages/client/src/index.ts
- packages/client/src/types.ts
- packages/crdt-yjs/src/doc.ts
- packages/crdt-yjs/src/index.ts
- packages/react/src/createBundle.tsx
- packages/react/src/createRoomBundle.tsx
- tests/e2e/src/components/CloudflareStorageRoom.tsx
- tests/e2e/src/components/NodeRedisStorageRoom.tsx
- tests/e2e/src/components/NodeStorageRoom.tsx
- tests/e2e/src/pluv-io/cloudflare.ts
- tests/e2e/src/pluv-io/node-redis.ts
- tests/e2e/src/pluv-io/node.ts
- tests/e2e/src/tests/cloudflare/storage/index.test.ts
- tests/e2e/src/tests/node-redis/storage/index.test.ts
- tests/e2e/src/tests/node/storage/index.test.ts
Closes https://github.com/pluv-io/pluv/issues/471
---
Added the capability to undo/redo changes made to yjs storage.
> feat(crdt-yjs): yjs undo redo

- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoServer.tsx
---
Fix spacing for type-safe code demo.
> fix: fix spacing for type-safe code demo

- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoClient.tsx
- apps/web/src/components/HomeTypeSafetyDemo/HomeTypeSafetyDemoServer.tsx
> fix: fix demo spacing

- apps/web/src/inputs/docs/Ecosystem.mdx
---
Added documentation for @pluv/addon-indexeddb.
> docs(www): add addon-indexeddb docs

- apps/web/src/inputs/docs/2--Quickstart.mdx
- apps/web/src/inputs/docs/@pluv_io/Node.js.mdx
- apps/web/src/inputs/docs/Ecosystem.mdx
---
Fix broken documentation links.
> fix: fix broken doc links

- apps/web/src/components/DocsLayout/DocsLayout.tsx
- apps/web/src/components/SiteWideLayout/SiteWideLayout.tsx
- apps/web/src/pages/index.tsx
- internal/react-components/src/molecules/TableOfContents/TableOfContents.tsx
---
Improve layout and scroll behavior for documentation.
> feat: updated scrolling and layout behaviors for documentation

- apps/web/src/inputs/docs/@pluv_client/API Reference.mdx
---
Add api reference for undo/redo for @pluv/client.
> docs: add api reference for undo redo

- apps/web/src/inputs/docs/@pluv_client/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_react/API Reference.mdx
- tests/e2e/src/components/NodeStorageRoom.tsx
---
Added documentation for undo/redo for @pluv/react.
> docs: add api reference for react undo redo

- .changeset/modern-fireants-explode.md
> chore(client): add-missing-changeset

- apps/web/src/components/DocsLayout/DocsLayout.tsx
> feat: simplify scroll styles

- apps/storybook/package.json
- apps/web/package.json
- internal/mdx-components/package.json
- pnpm-lock.yaml
> chore: bump mdx deps

- .changeset/bright-squids-vanish.md
- packages/io/package.json
- pnpm-lock.yaml
---
Bumped dependency jose to latest major.
> chore: bump jose

- .changeset/fresh-paws-relax.md
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/cli/src/commands/build.tsx
- packages/cli/src/schemas/ZodPluvConfig.ts
- packages/cli/src/schemas/index.ts
- packages/cli/src/utils/buildApp.ts
- packages/cli/src/utils/config.ts
- pnpm-lock.yaml
---
Added support for passing in environment variables to the pluv cli.
> feat(pluv): added env

- .changeset/fresh-paws-relax.md
> chore: fix changeset

- .changeset/two-rivers-repair.md
- packages/cli/package.json
- packages/cli/src/utils/buildApp.ts
---
Fix environment variables not properly replacing.
> fix(pluv): fix environment variables not replacing

- .changeset/smart-glasses-destroy.md
- packages/cli/package.json
- packages/cli/src/schemas/ZodPluvConfig.ts
- packages/cli/src/utils/buildApp.ts
- pnpm-lock.yaml
---
Added support for .env files (`.env` by default).
> feat(cli): added support for .env files

- packages/crdt-yjs/src/doc/CrdtYjsDoc.ts
---
Fix broken crdt yjs object.
> fix: fix broken crdt yjs object

- packages/crdt-yjs/src/array/CrdtYjsArray.ts
- packages/crdt-yjs/src/constants.ts
- packages/crdt-yjs/src/map/CrdtYjsMap.ts
- packages/crdt-yjs/src/object/CrdtYjsObject.ts
- packages/crdt-yjs/src/xmlElement/CrdtYjsXmlElement.ts
- packages/crdt-yjs/src/xmlFragment/CrdtYjsXmlFragment.ts
> fix(crdt-yjs): fix types

- packages/io/package.json
- pnpm-lock.yaml
---
Removed now unnecessary yjs peer dependency.
> chore(io): removed now unnecessary yjs peer dependency

- packages/crdt-loro/src/doc/CrdtLoroDocFactory.ts
- packages/crdt-yjs/src/doc/CrdtYjsDocFactory.ts
- packages/crdt-yjs/tsconfig.json
- packages/crdt/src/AbstractCrdtDocFactory.ts
- packages/react/src/createRoomBundle.tsx
- packages/react/src/index.ts
---
Simplify how room initial storage is passed in (to be more like how it was before).
> feat(react): update how room initial storage is passed in

- .changeset/rude-deers-help.md
- packages/io/README.md
---
Removed outdated portion of the README.
> chore: updated README

- .changeset/giant-goats-drive.md
- .gitignore
- packages/io/package.json
- packages/io/src/index.ts
- packages/io/src/version.ts
- pnpm-lock.yaml
---
Export the downloaded version of `@pluv/io`.
> feat(io): emit io version

- apps/web/src/inputs/docs/@pluv_io/Cloudflare Workers.mdx
---
Fix cloudflare doc missing env in durable object example.
> chore: fix missing env param in cloudflare docs

- apps/web/src/inputs/docs/@pluv_io/Cloudflare Workers.mdx
---
Fix missing params in register example in cloudflare docs.
> docs: fix missing params in cloudflare docs register example

- .changeset/tiny-oranges-run.md
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
- packages/io/src/authorize.ts
- packages/io/src/createIO.ts
- packages/platform-cloudflare/src/createPluvHandler.ts
- packages/platform-node/src/createPluvHandler.ts
- packages/types/src/pluv.ts
- tests/e2e/src/server/yjs/node-redis/cluster.ts
- tests/e2e/src/server/yjs/node-redis/index.ts
---
Added ability to get platform context in the authorize config when creating an IO instance.
> feat(io): function authorize

- apps/web/src/inputs/docs/@pluv_io/API Reference.mdx
---
Updated docs so that `io.createToken` includes the platform context.
> docs: updated io.createToken docs to include the platform context

- apps/web/src/inputs/docs/@pluv_io/Authorization.mdx
---
Added missing context in authorization doc.
> docs: added missing context in authorization doc

- packages/cli/src/schemas/ZodPluvConfig.ts
> fix(cli): fix env type

- .changeset/purple-gorillas-raise.md
- packages/react/src/createRoomBundle.tsx
- tests/e2e/src/demo/ChatRoom.tsx
- tests/e2e/src/demo/pluv.ts
> feat(react): event proxy

- .changeset/brown-pandas-agree.md
- packages/client/src/PluvRoom.ts
> feat(client): broadcast proxy

- .changeset/tame-tables-warn.md
- packages/react/src/createRoomBundle.tsx
- tests/e2e/src/demo/ChatRoom.tsx
---
Added broadcast proxy for the @pluv/react package that allows cmd + clicking to navigate to the original procedure.
> feat(react): broadcast proxy

- .changeset/fast-cats-drum.md
- package.json
- packages/client/src/PluvRoom.ts
- packages/io/src/IORoom.ts
---
Added broadcast proxy to `IORoom` to be able to broadcast an event to a room, and cmd + click on the event to reference the original procedure.
> feat(io): broadcast proxy

- packages/client/README.md
- packages/platform-cloudflare/README.md
- packages/platform-node/README.md
- packages/react/README.md
> chore: update readmes

- apps/web/src/inputs/docs/1--Introduction.mdx
- apps/web/src/inputs/docs/2--Quickstart.mdx
- apps/web/src/inputs/docs/@pluv_client/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_client/Create Client.mdx
- apps/web/src/inputs/docs/@pluv_io/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_io/Authorization.mdx
- apps/web/src/inputs/docs/@pluv_io/Cloudflare Workers.mdx
- apps/web/src/inputs/docs/@pluv_io/Define Events.mdx
- apps/web/src/inputs/docs/@pluv_io/Node.js.mdx
- apps/web/src/inputs/docs/@pluv_react/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_react/Create Bundle.mdx
- apps/web/src/inputs/docs/@pluv_react/Custom Events.mdx
- apps/web/src/inputs/docs/@pluv_react/Yjs Storage.mdx
---
Update api references with new changes.
> docs: update api references

- .changeset/lazy-seas-return.md
- packages/client/src/OtherNotifier.ts
- packages/client/src/PluvRoom.ts
- packages/types/src/general.ts
- packages/types/src/pluv.ts
---
Fix other users' not being tracked when the users are unauthorized.
> fix: fix unauthorized presence

- .changeset/heavy-ghosts-help.md
- packages/client/src/AbstractRoom.ts
- packages/client/src/MockedRoom.ts
- packages/client/src/PluvRoom.ts
- packages/client/src/types.ts
---
Update `PluvRoom.updateMyPresence` to allow passing in a callback function that exposes the previous presence value.
> feat(client): update my presence action callback

- .changeset/eleven-pens-destroy.md
- packages/react/src/createRoomBundle.tsx
---
Update `updateMyPresence` function from the `useMyPresence` hook to simply forward the function from the `PluvRoom`.
> feat(react): stable update my presence

- apps/web/src/components/CodeBlock/CodeBlock.tsx
- apps/web/src/components/HomeFeaturesSection/HomeFeaturesSection.tsx
- apps/web/src/components/HomeFeaturesSection/HomeFeaturesSectionFeature.tsx
- apps/web/src/components/HomeHero/HomeHero.tsx
- apps/web/src/components/ServerCodeBlock/ServerCodeBlock.tsx
- apps/web/src/components/SiteWideFooter/SiteWideFooter.tsx
- internal/react-components/client/molecules/DataTable/DataTablePagination.tsx
---
Upgrade website with style improvements.
> feat: style improvements

- .github/workflows/close-inactive-issues.yml
---
Added github action to close stale actions.
> ci: add github action to close stale issues

- .github/workflows/close-inactive-issues.yml
---
Update stale github action.
> ci: update stale action

- .changeset/curly-doors-attack.md
- packages/io/src/AbstractPlatform.ts
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
- packages/io/src/PluvProcedure.ts
- packages/io/src/PluvServer.ts
- packages/io/src/index.ts
- packages/platform-cloudflare/src/CloudflarePlatform.ts
- packages/platform-cloudflare/src/createPluvHandler.ts
- packages/platform-node/src/NodePlatform.ts
- packages/platform-node/src/createPluvHandler.ts
- tests/e2e/src/server/yjs/node-redis/index.ts
---
Remove platform event context.
> feat(io): remove platform event context

- .changeset/smart-colts-dress.md
- packages/io/src/AbstractPlatform.ts
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
- packages/io/src/PluvProcedure.ts
- packages/io/src/PluvRouter.ts
- packages/io/src/PluvServer.ts
- packages/io/src/authorize.ts
- packages/io/src/createIO.ts
- packages/io/src/index.ts
- packages/io/src/types.ts
- packages/platform-cloudflare/src/CloudflarePlatform.ts
- packages/platform-cloudflare/src/createPluvHandler.ts
---
Require `DurableObjectState` in `PluvServer.getRoom`.
> feat(platform cloudflare): require durable object state

- package.json
- pnpm-lock.yaml
> chore: bump pnpm

- apps/web/src/components/CodeBlock/CodeBlock.tsx
- apps/web/src/components/HomeCodeDemo/HomeCodeDemo.tsx
- apps/web/src/components/ServerCodeBlock/ServerCodeBlock.tsx
- internal/mdx-components/src/MdxH1.tsx
- internal/mdx-components/src/MdxH2.tsx
- internal/mdx-components/src/MdxH3.tsx
- internal/mdx-components/src/MdxH4.tsx
- internal/react-components/client/molecules/Breadcrumbs/BreadcrumbsItem.tsx
- internal/react-components/client/molecules/DataTable/DataTablePagination.tsx
- internal/react-components/either/atoms/Button/Button.tsx
---
Fix mobile responsiveness.
> fix: fix mobile responsiveness

- apps/web/src/app/layout.tsx
- apps/web/src/components/CodeBlock/CodeBlock.tsx
- apps/web/src/components/CodeBlock/CodeBlockProvider.tsx
- apps/web/src/components/CodeBlock/context.ts
- apps/web/src/components/CodeBlock/index.ts
- apps/web/src/components/ServerCodeBlock/ServerCodeBlock.tsx
- apps/web/src/utils/getShiki.ts
---
Cache shiki to prevent excess loading and instances of shiki.
> chore: cache shiki to prevent excess load

- .changeset/gentle-ways-melt.md
- packages/client/src/PluvRoom.ts
- packages/io/src/AbstractPlatform.ts
- packages/io/src/AbstractWebSocket.ts
- packages/io/src/IORoom.ts
- packages/io/src/index.ts
- packages/platform-cloudflare/src/CloudflarePlatform.ts
- packages/platform-cloudflare/src/CloudflareWebSocket.ts
- packages/platform-cloudflare/src/PersistanceCloudflare.ts
- packages/platform-cloudflare/src/index.ts
- packages/platform-cloudflare/src/utils/index.ts
- packages/platform-cloudflare/src/utils/partitionByLength.ts
- packages/platform-node/src/NodePlatform.ts
- packages/platform-node/src/NodeWebSocket.ts
---
Adds initial support for Cloudflare Worker WebSocket hibernation.
> chore: update platforms in preparation for websocket hibernation support

- apps/web/src/inputs/docs/@pluv_io/Cloudflare Workers.mdx
- packages/io/src/IORoom.ts
---
Update docs for registering websockets for Cloudflare.
> docs: update cloudflare register

- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
- packages/io/src/constants.ts
---
Improve detection of stale sessions.
> fix: improve detection of stale sessions

- .changeset/cuddly-frogs-develop.md
- packages/client/src/PluvRoom.ts
- packages/io/src/AbstractPlatform.ts
- packages/io/src/AbstractWebSocket.ts
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
- packages/io/src/PluvServer.ts
- packages/io/src/index.ts
- packages/io/src/types.ts
- packages/platform-cloudflare/src/CloudflarePlatform.ts
- packages/platform-cloudflare/src/CloudflareWebSocket.ts
- packages/platform-cloudflare/src/constants.ts
- packages/platform-cloudflare/src/createPluvHandler.ts
- packages/platform-node/src/NodePlatform.ts
- packages/platform-node/src/NodeWebSocket.ts
- packages/platform-node/src/createPluvHandler.ts
---
Added support for Cloudflare's websocket hibernation api.
> chore(io): platform restructure

- .changeset/eight-shrimps-cry.md
- packages/platform-cloudflare/src/constants.ts
---
Temporarily revert default cloudflare platform mode to attached.
> chore: revert default cloudflare platform mode

- .changeset/sharp-llamas-hug.md
- apps/server-cloudflare/src/pluv-io.ts
- packages/client/src/PluvRoom.ts
- packages/io/src/AbstractPlatform.ts
- packages/io/src/AbstractWebSocket.ts
- packages/io/src/PluvIO.ts
- packages/io/src/PluvServer.ts
- packages/platform-cloudflare/src/CloudflarePlatform.ts
- packages/platform-cloudflare/src/CloudflareWebSocket.ts
- packages/platform-cloudflare/src/constants.ts
- packages/platform-cloudflare/src/platformCloudflare.ts
- packages/platform-node/src/NodePlatform.ts
- packages/platform-node/src/NodeWebSocket.ts
---
* Fix frequent disconnects on `@pluv/platform-cloudflare` due to incorrect heartbeat handling.
* Updated default `"mode"` of `@pluv/platform-cloudflare` to be `"detached"` (i.e. use Cloudflare Worker's WebSocket Hibernation API by default).
> fix(platform cloudflare): fix heartbeat

- internal/react-components/client/atoms/Avatar/AvatarAnimal.tsx
---
Fix the initial flicker on user avatars in the home page.
> fix: fix the avatar flicker

- apps/web/src/inputs/docs/@pluv_io/Cloudflare Workers.mdx
- apps/web/src/inputs/docs/@pluv_io/Node.js.mdx
- packages/platform-cloudflare/src/createPluvHandler.ts
---
Update docs for Cloudflare Workers on supporting WebSocket hibernation.
> docs: update cloudflare worker docs

- apps/web/src/inputs/docs/@pluv_io/Cloudflare Workers.mdx
---
Improve text wrap in docs.
> docs: improve text wrap

- packages/io/src/AbstractPlatform.ts
- packages/io/src/PluvIO.ts
---
Hide properties that are not intended to be public.
> chore(io): hide non-public properties

- apps/web/src/inputs/docs/@pluv_io/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_io/Loading Storage.mdx
---
Update docs with breaking changes.
> docs: update docs with breaking changes

- .changeset/violet-trainers-talk.md
- packages/io/src/IORoom.ts
- packages/io/src/PluvServer.ts
- packages/platform-cloudflare/src/createPluvHandler.ts
---
Fix messages and storage being lost when the room is restored from Cloudflare's WebSocket hibernation.
> fix(io): fix messages being lost when restoring from hibernation

- apps/server-cloudflare/src/pluv-io.ts
---
Update docs homepage to use Cloudflare Worker websocket hibernation.
> docs: use websocket hibernation

- apps/web/src/components/HomeCodeDemo/HomeCodeDemo.tsx
- apps/web/src/inputs/docs/@pluv_io/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_io/Authorization.mdx
- apps/web/src/inputs/docs/@pluv_io/Cloudflare Workers.mdx
- apps/web/src/inputs/docs/@pluv_io/Node.js.mdx
---
Update docs with breaking changes.
> docs: update with breaking changes

- .changeset/gorgeous-hairs-peel.md
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
- packages/io/src/PluvRouter.ts
- packages/io/src/PluvServer.ts
- packages/platform-cloudflare/src/createPluvHandler.ts
- packages/platform-node/src/createPluvHandler.ts
- packages/types/src/pluv.ts
---
Consolidate internal properties.
> refactor(io): consolidate internals

- .changeset/light-bulldogs-drum.md
- packages/io/src/AbstractPlatform.ts
> chore(io): update accessor

- .changeset/smooth-bananas-cheat.md
- packages/io/src/IORoom.ts
- packages/io/src/PluvServer.ts
---
Fixed not passing all properties to the platform initialization.
> fix(io): fix configuring platform

- .changeset/seven-clocks-marry.md
- packages/platform-cloudflare/src/CloudflarePlatform.ts
- packages/platform-node/src/NodePlatform.ts
---
Update `@pluv/platform-cloudflare` and `@pluv/platform-node` so that exact properties are used in its initialization.
> chore(platform cloudflare): exact initialization

- .changeset/beige-gorillas-serve.md
- .changeset/rotten-peaches-roll.md
- apps/web/src/components/HomeCodeDemo/HomeCodeDemo.tsx
- apps/web/src/components/HomeIntroStep3/HomeIntroStep3Code.tsx
- apps/web/src/components/HomeIntroStep4/HomeIntroStep4Code.tsx
- apps/web/src/components/HomeIntroStep5/HomeIntroStep5Code.tsx
- apps/web/src/inputs/docs/@pluv_client/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_client/Create Client.mdx
- apps/web/src/inputs/docs/@pluv_client/Create Rooms.mdx
- apps/web/src/pluv-io/cloudflare.ts
- packages/client/src/PluvClient.ts
- packages/client/src/PluvRoom.ts
- packages/client/src/createClient.ts
- packages/client/src/index.ts
- packages/react/src/createBundle.tsx
- packages/react/src/createRoomBundle.tsx
- tests/e2e/src/demo/pluv.ts
- tests/e2e/src/pluv-io/loro/node.ts
- tests/e2e/src/pluv-io/noop/node.ts
- tests/e2e/src/pluv-io/yjs/cloudflare.ts
- tests/e2e/src/pluv-io/yjs/node-redis.ts
- tests/e2e/src/pluv-io/yjs/node.ts
---
Move endpoints config from client to room.
> feat: move endpoints config from client to room

- apps/web/src/inputs/docs/@pluv_react/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_react/History.mdx
- apps/web/src/inputs/docs/@pluv_react/Presence.mdx
- apps/web/src/inputs/docs/@pluv_react/Yjs Storage.mdx
---
Update docs with more breaking changes about endpoints.
> docs: update docs with more breaking changes

- .changeset/pink-weeks-leave.md
- apps/web/src/components/HomeCodeDemo/HomeCodeDemo.tsx
- apps/web/src/components/HomeIntroStep3/HomeIntroStep3Code.tsx
- apps/web/src/pluv-io/cloudflare.ts
- packages/addon-indexeddb/src/addonIndexedDB.ts
- packages/client/src/PluvClient.ts
- packages/client/src/PluvRoom.ts
- packages/client/src/createClient.ts
- packages/client/src/index.ts
- packages/react/src/createBundle.tsx
- packages/react/src/createRoomBundle.tsx
- tests/e2e/src/pluv-io/loro/node.ts
- tests/e2e/src/pluv-io/noop/node.ts
- tests/e2e/src/pluv-io/yjs/cloudflare.ts
- tests/e2e/src/pluv-io/yjs/node-redis.ts
- tests/e2e/src/pluv-io/yjs/node.ts
---
Update endpoint params to use a parameterized object that also accepts metadata.
> feat(client): update endpoint params

- apps/web/src/inputs/docs/@pluv_client/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_client/Create Client.mdx
- apps/web/src/inputs/docs/@pluv_io/Authorization.mdx
- apps/web/src/inputs/docs/@pluv_react/Presence.mdx
- apps/web/src/inputs/docs/@pluv_react/Yjs Storage.mdx
---
Update docs with endpoint breaking changes.
> docs: update docs with endpoint breaking changes

- apps/web/src/inputs/docs/@pluv_client/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_client/Create Client.mdx
---
Fix comment about defaults.
> docs: fix defaults comment

- .changeset/pink-guests-search.md
- packages/io/src/IORoom.ts
- pnpm-lock.yaml
- tests/e2e/package.json
---
Broadcast events that are not defined as procedures as-is to connected peers.
> feat(io): passthrough event

- packages/crdt-loro/package.json
- pnpm-lock.yaml
- tests/e2e/package.json
> chore: bump loro

- apps/web/next-env.d.ts
- pnpm-lock.yaml
> chore: bump nextjs-toploader

- apps/web/src/inputs/docs/@pluv_client/API Reference.mdx
---
Update copies on the client api-reference docs.
> docs: update client docs

- apps/web/src/components/HomeCodeDemo/HomeCodeDemo.tsx
- apps/web/src/inputs/docs/@pluv_react/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_react/Presence.mdx
---
Fix zod references in docs.
> docs: fix zod references

- apps/web/src/inputs/docs/@pluv_client/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_client/Client vs Server Events.mdx
- apps/web/src/inputs/docs/@pluv_client/Define Events.mdx
---
Added docs for client events.
> docs: added docs for client events

- .changeset/quick-readers-applaud.md
- packages/platform-pluv/.eslintrc.js
- packages/platform-pluv/package.json
- packages/platform-pluv/src/PluvIO.ts
- packages/platform-pluv/src/PluvPlatform.ts
- packages/platform-pluv/src/createIO.ts
- packages/platform-pluv/src/index.ts
- packages/platform-pluv/src/schemas.ts
- packages/platform-pluv/tsconfig.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
---
Add new package `@pluv/platform-pluv`.
> feat(platform pluv): add platform pluv

- .changeset/five-needles-rule.md
- packages/client/src/PluvClient.ts
- packages/client/src/PluvRoom.ts
---
Add `publicKey` property to `createClient`.
> feat(client): client public key

- .changeset/nice-brooms-occur.md
- packages/io/src/index.ts
---
Export the `authorize` utility from `@pluv/io`.
> feat(io): export authorize util

- .changeset/honest-dryers-reply.md
- packages/platform-pluv/src/PluvIO.ts
---
Add missing `publicKey` param to `createIO`.
> fix(platform-pluv): add missing public key

- .changeset/calm-rocks-roll.md
- packages/platform-cloudflare/src/index.ts
- packages/platform-node/src/index.ts
---
Export types for `NodePlatform` and `CloudflarePlatform`.
> feat: export platform types

- .changeset/chilled-books-behave.md
- apps/web/src/inputs/docs/@pluv_io/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_io/Authorization.mdx
- packages/io/src/AbstractPlatform.ts
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
- packages/io/src/PluvProcedure.ts
- packages/io/src/PluvRouter.ts
- packages/io/src/PluvServer.ts
- packages/io/src/authorize.ts
- packages/io/src/createIO.ts
- packages/io/src/index.ts
- packages/io/src/types.ts
- packages/platform-cloudflare/src/CloudflarePlatform.ts
- packages/platform-cloudflare/src/createPluvHandler.ts
- packages/platform-node/src/NodePlatform.ts
- packages/platform-node/src/createPluvHandler.ts
- packages/platform-pluv/src/PluvPlatform.ts
- tests/e2e/src/server/yjs/node-redis/index.ts
---
Fixed incorrect context types for platforms.
> fix(io): fix io platform context types

- .changeset/chilled-books-behave.md
- .changeset/shiny-trainers-call.md
- apps/web/src/inputs/docs/@pluv_io/Cloudflare Workers.mdx
- apps/web/src/inputs/docs/@pluv_io/Node.js.mdx
- packages/platform-cloudflare/src/createPluvHandler.ts
- packages/platform-node/src/createPluvHandler.ts
---
Update params for the `authorize` property on `createPluvHandler`.
> feat: update create pluv handler authorize params

- .changeset/fluffy-fireants-beam.md
- apps/web/src/inputs/docs/@pluv_io/API Reference.mdx
- apps/web/src/inputs/docs/@pluv_io/Cloudflare Workers.mdx
- apps/web/src/inputs/docs/@pluv_io/Node.js.mdx
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
- packages/io/src/PluvProcedure.ts
- packages/io/src/PluvRouter.ts
- packages/io/src/PluvServer.ts
- packages/io/src/createIO.ts
- packages/io/src/types.ts
---
Update the `context` prop on `createIO` to allow function context types.
> feat(io): support function context types

- .changeset/green-wolves-swim.md
- packages/platform-pluv/src/PluvIO.ts
> feat(platform-pluv): update token endpoint

- .changeset/five-moose-cry.md
- packages/react/src/index.ts
---
Export the `register` helper.
> feat(react): export register

- .changeset/brown-shoes-nail.md
- packages/platform-pluv/src/PluvIO.ts
---
Added properties for internal use only.
> chore(platform-pluv): add internal properties

- apps/web/package.json
- pnpm-lock.yaml
> chore: bump shiki

- .changeset/clever-countries-look.md
- package.json
- packages/platform-cloudflare/src/CloudflarePlatform.ts
- packages/platform-cloudflare/src/platformCloudflare.ts
- packages/platform-node/src/NodePlatform.ts
- packages/platform-node/src/platformNode.ts
> feat: room meta context

- .changeset/friendly-ghosts-drum.md
- packages/platform-cloudflare/src/CloudflarePlatform.ts
- packages/platform-cloudflare/src/platformCloudflare.ts
- packages/platform-node/src/NodePlatform.ts
- packages/platform-node/src/platformNode.ts
---
Fix meta type to allow nested json.
> fix: fix meta type to allow nested json

- .changeset/cuddly-trainers-sort.md
- packages/platform-pluv/src/PluvIO.ts
---
Fix event payload types to only contain JSON serializable fields.
> fix(platform pluv): fix events

- .changeset/pretty-trains-kiss.md
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
- packages/io/src/PluvServer.ts
- packages/io/src/index.ts
- packages/io/src/types.ts
- packages/platform-pluv/src/PluvIO.ts
---
Added user connection events.
> feat(io): user connection events

- .changeset/pretty-yaks-grow.md
- packages/platform-pluv/src/PluvIO.ts
- packages/platform-pluv/src/schemas.ts
---
Enable user connection events.
> feat(platform-pluv): connect user connection events

- .changeset/tough-crabs-buy.md
- packages/platform-pluv/src/PluvIO.ts
- packages/platform-pluv/src/constants.ts
- packages/platform-pluv/src/shared/createHmac.ts
- packages/platform-pluv/src/shared/getCrypto.ts
- packages/platform-pluv/src/shared/index.ts
- packages/platform-pluv/src/shared/signWebhook.ts
- packages/platform-pluv/src/shared/timingSafeEqual.ts
- packages/platform-pluv/src/shared/verifyWebhook.ts
---
Add webhook validation, and prevent setting webhooks if a webhook secret is not present.
> feat(platform-pluv): add webhook validation

- packages/crdt-loro/package.json
- packages/crdt-loro/src/doc/CrdtLoroDoc.ts
- pnpm-lock.yaml
- tests/e2e/package.json
> chore: bump loro-crdt

- .changeset/beige-pigs-yell.md
- packages/react/src/createBundle.tsx
- packages/react/src/index.ts
---
Fix event proxy types for client-side events.
> fix(react): fix client event types

- .changeset/cold-boats-prove.md
---
Add missing bumo loro-crdt changeset.
> chore: added missing bump loro-crdt changeset

- apps/web/tsconfig.json
> fix: web types

- .changeset/silent-dancers-lay.md
- packages/platform-pluv/src/PluvIO.ts
---
Move webhooks to base path.
> feat(platform-pluv): move webhooks to base path

- .changeset/popular-cooks-divide.md
- packages/crdt-loro/package.json
---
Require peer loro-crdt@^1.0.0.
> feat(crdt-loro): require loro 1.0

- .changeset/twenty-fireants-build.md
- packages/react/package.json
---
Allow peer `react@^19.0.0`.
> feat(react): allow react19

- docs/@pluv__client/api_reference.mdx
- docs/@pluv__client/client_vs_server_events.mdx
- docs/@pluv__client/create_client.mdx
- docs/@pluv__client/create_rooms.mdx
- docs/@pluv__client/define_events.mdx
- docs/@pluv__io/api_reference.mdx
- docs/@pluv__io/authorization.mdx
- docs/@pluv__io/cloudflare_workers.mdx
- docs/@pluv__io/define_events.mdx
- docs/@pluv__io/loading_storage.mdx
- docs/@pluv__io/nodejs.mdx
- docs/@pluv__io/pubsub.mdx
- docs/@pluv__react/api_reference.mdx
- docs/@pluv__react/create_bundle.mdx
- docs/@pluv__react/create_rooms.mdx
- docs/@pluv__react/custom_events.mdx
- docs/@pluv__react/history.mdx
- docs/@pluv__react/presence.mdx
- docs/@pluv__react/yjs_storage.mdx
- docs/ecosystem.mdx
- docs/introduction.mdx
- docs/quickstart.mdx
> feat: move docs

- docs/introduction.mdx
---
Added introduction frontmatter.
> docs: added introduction frontmatter

- docs/@pluv__client/api_reference.mdx
- docs/@pluv__client/client_vs_server_events.mdx
- docs/@pluv__client/create_client.mdx
- docs/@pluv__client/create_rooms.mdx
- docs/@pluv__client/define_events.mdx
- docs/@pluv__io/api_reference.mdx
- docs/@pluv__io/authorization.mdx
- docs/@pluv__io/cloudflare_workers.mdx
- docs/@pluv__io/define_events.mdx
- docs/@pluv__io/loading_storage.mdx
- docs/@pluv__io/nodejs.mdx
- docs/@pluv__io/pubsub.mdx
- docs/@pluv__react/api_reference.mdx
- docs/@pluv__react/create_bundle.mdx
- docs/@pluv__react/create_rooms.mdx
- docs/@pluv__react/custom_events.mdx
- docs/@pluv__react/history.mdx
- docs/@pluv__react/presence.mdx
- docs/@pluv__react/yjs_storage.mdx
- docs/ecosystem.mdx
- docs/quickstart.mdx
> docs: added other frontmatters

- .changeset/poor-flies-report.md
- packages/io/src/IORoom.ts
---
Fix `onUserDisconnected` event not being emitted.
> fix(io): fix not emitting onUserDisconnected event

- packages/platform-pluv/src/PluvPlatform.ts
---
Fix `@pluv/platform-pluv`'s authorize config validation.
> fix(platform-pluv): fix authorize config validation

- packages/platform-pluv/src/PluvPlatform.ts
> chore: delete unused import

- .changeset/old-maps-approve.md
- packages/io/src/IORoom.ts
- packages/io/src/PluvProcedure.ts
- packages/io/src/types.ts
- tests/e2e/src/server/yjs/cloudflare/pluv-io.ts
---
Improve session resolver context types.
> feat(io): improve session resolver context types

- packages/crdt-loro/src/loro.ts
- packages/crdt-loro/src/movableList.ts
- packages/crdt-loro/src/tree.ts
> feat(crdt-loro): add missing crdt types

- packages/crdt-loro/src/doc/CrdtLoroDoc.ts
---
Cleanup deprecated method.
> chore: cleanup deprecated method

- .changeset/quick-gorillas-lick.md
- packages/platform-pluv/src/PluvPlatform.ts
---
Remove unused `authorize.required` validation.
> chore(platform-pluv): remove unused required validation

- pnpm-lock.yaml
- tests/e2e/package.json
- tests/e2e/src/server/loro/node/index.ts
- tests/e2e/src/server/noop/node/index.ts
- tests/e2e/src/server/yjs/node-redis/index.ts
- tests/e2e/src/server/yjs/node/index.ts
> chore: bump commander

- .changeset/fluffy-shoes-stare.md
- packages/io/src/AbstractPlatform.ts
- packages/io/src/PluvServer.ts
- packages/platform-cloudflare/src/createPluvHandler.ts
---
Fix cloudflare emitted about `platformCloudflare` not supporting `fetch` when deployed to Cloudflare Workers.
> fix(io): fix cloudflare fetch error

- apps/storybook/package.json
- pnpm-lock.yaml
---
Bump babel-loader to latest major.
> chore: bump babel-loader

- .changeset/cold-candles-cheat.md
- packages/io/src/PluvIO.ts
- packages/io/src/types.ts
- packages/platform-cloudflare/src/CloudflarePlatform.ts
- packages/platform-node/src/NodePlatform.ts
- packages/platform-pluv/src/PluvPlatform.ts
- pnpm-lock.yaml
- tests/e2e/package.json
- tests/e2e/src/tests/types/pluv.ts
---
Narrow platform config types.
> feat(io): narrow platform config types

- .changeset/shaggy-pants-invent.md
- packages/client/src/PluvClient.ts
- packages/client/src/PluvRoom.ts
- packages/client/src/index.ts
- packages/client/src/types.ts
---
Added support for dynamic public keys.
> feat(client): dynamic public key

- .changeset/yummy-places-press.md
- packages/client/src/PluvClient.ts
---
Add missing metadata validation.
> fix(client): add missing metadata validation

- .changeset/mean-jobs-juggle.md
- packages/client/src/PluvClient.ts
> fix(client): fix client public key

- .changeset/gentle-turkeys-kneel.md
- packages/io/src/AbstractPlatform.ts
- packages/io/src/AbstractWebSocket.ts
- packages/io/src/IORoom.ts
- packages/io/src/PluvServer.ts
- packages/platform-cloudflare/src/CloudflarePlatform.ts
- packages/platform-cloudflare/src/CloudflareWebSocket.ts
- packages/platform-node/src/NodePlatform.ts
- packages/platform-pluv/src/PluvPlatform.ts
- packages/pubsub-redis/src/PubSubRedis.ts
- tests/e2e/src/components/yjs/cloudflare/StorageRoom.tsx
---
Fix hibernated Cloudflare Worker websockets not updating their last ping timer and causing them to be disconnected as a result.
> fix(platform-cloudflare): fix connection timeouts

- .changeset/proud-grapes-happen.md
- packages/io/src/IORoom.ts
- packages/io/src/types.ts
- packages/io/tsconfig.json
---
Log error on user connection events.
> feat(io): log error on user join disconnect

- .changeset/ten-stars-shout.md
- packages/platform-pluv/package.json
- packages/platform-pluv/src/PluvPlatform.ts
- pnpm-lock.yaml
---
Fixed webhook signature verification
> fix(platform pluv): fix webhook verification

- .changeset/upset-hats-write.md
- packages/client/src/MockedRoom.ts
- packages/client/src/PluvRoom.ts
- packages/io/src/AbstractWebSocket.ts
- packages/io/src/IORoom.ts
- packages/io/src/PluvServer.ts
- packages/types/src/pluv.ts
---
Updated internal event names to be in camelCase instead of PASCAL_CASE.
> feat(io): update event names

- .changeset/brown-lions-matter.md
- packages/platform-pluv/src/PluvPlatform.ts
- packages/platform-pluv/src/constants.ts
-  [x] I have followed every step in the [contributing guide](https://github.com/pluv-io/pluv/blob/master/CONTRIBUTING.md) (updated 2023-01-05).
---
Fixed webhook signature validation.
> fix(platform-pluv): webhook signature validation

- .changeset/mighty-rats-start.md
- packages/io/src/PluvServer.ts
- packages/platform-pluv/src/PluvPlatform.ts
- packages/platform-pluv/src/index.ts
- packages/platform-pluv/src/platformPluv.ts
- packages/platform-pluv/src/types.ts
---
Fixed undefined event contexts.
> fix(platform-pluv): undefined event context

- .changeset/gold-schools-relax.md
- packages/platform-pluv/src/PluvPlatform.ts
---
Fix the `onUserDisconnected` event triggering when `onUserConnected` event triggers.
> fix(platform-pluv): fix disconnect event trigger

- .changeset/funny-swans-lick.md
- packages/platform-pluv/src/PluvPlatform.ts
---
Updated internal event handlers to return more meaningful status codes and room identifiers.
> fix(platform-pluv): richer event payload

- packages/platform-pluv/src/PluvPlatform.ts
- packages/platform-pluv/src/schemas.ts
- packages/platform-pluv/src/shared/HttpError.ts
- packages/platform-pluv/src/shared/createErrorResponse.ts
- packages/platform-pluv/src/shared/createSuccessResponse.ts
- packages/platform-pluv/src/shared/index.ts
- packages/platform-pluv/src/types.ts
---
Cleanup handling of responses.
> refactor(platform-pluv): cleanup handling of responses

- docs/@pluv__platform_cloudflare/hosting_on_cloudflare.mdx
> docs: rename cloudflare doc

- apps/web/src/inputs/docs/2--Quickstart.mdx
- apps/web/src/inputs/docs/@pluv_io/Authorization.mdx
- apps/web/src/inputs/docs/@pluv_io/Node.js.mdx
- docs/@pluv__io/authorization.mdx
- docs/@pluv__platform_node/hosting_on_nodejs.mdx
- docs/@pluv__platform_pluv/getting_started.mdx
- docs/quickstart.mdx
---
Added `@pluv/platform-pluv` getting started documentation.
> docs: platform pluv getting started

- .changeset/gold-papayas-care.md
- packages/client/src/PluvRoom.ts
---
Fix default ws endpoint for when `@pluv/platform-pluv` is being used.
> fix(client): fix default ws endpoint

- .changeset/heavy-bananas-argue.md
- packages/client/src/EventNotifier.ts
- packages/client/src/PluvClient.ts
- packages/client/src/PluvRoom.ts
- packages/types/src/pluv.ts
---
Fix broken event and broadcast type narrowing for `PluvRoom.event` and `PluvRoom.broadcast`.
> fix(client): fix event types

- .changeset/fine-teeth-smell.md
- packages/client/src/PluvRoom.ts
- packages/client/src/UsersManager.ts
---
Fix cases where the user's own presence was getting updated excessively, and without re-triggering subscriptions.
> fix(client): fix over patching my presence

- .changeset/config.json
- pnpm-workspace.yaml
---
Fix workspace configs referencing stale modules that no-longer exist.
> fix: fix workspace configs referencing stale modules

- .changeset/cruel-feet-return.md
- packages/react/src/createBundle.tsx
---
Update `MockedRoomContext` value to mirror `PluvRoomContext`.
> feat(react): update mocked room context

- .changeset/deep-cameras-roll.md
- packages/platform-cloudflare/src/CloudflareWebSocket.ts
- packages/platform-node/src/createPluvHandler.ts
- tests/e2e/src/server/yjs/node-redis/index.ts
---
Improve websocket 1011 error codes to instead be 1003 for invalid connection data.
> feat: narrower websocket error codes

- .changeset/silly-words-retire.md
- packages/io/src/AbstractPersistence.ts
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
- packages/io/src/PluvServer.ts
- packages/persistence-cloudflare-transactional-storage/src/PersistenceCloudflareTransactionalStorage.ts
- packages/persistence-redis/src/PersistenceRedis.ts
---
Fix not always fully running clean-up effects on the `IORoom` after websocket sessions are closed.
> fix(io): fix session close cleanup

- .github/CODEOWNERS
- docs/@pluv__io/api_reference.mdx
- docs/@pluv__io/authorization.mdx
- docs/@pluv__platform_cloudflare/hosting_on_cloudflare.mdx
- docs/@pluv__platform_node/hosting_on_nodejs.mdx
- docs/@pluv__react/history.mdx
- packages/client/src/PluvRoom.ts
- packages/io/src/AbstractWebSocket.ts
- packages/io/src/IORoom.ts
- packages/react/src/createBundle.tsx
- tests/e2e/src/pluv-io/loro/node.ts
- tests/e2e/src/pluv-io/yjs/cloudflare.ts
- tests/e2e/src/pluv-io/yjs/node-redis.ts
- tests/e2e/src/pluv-io/yjs/node.ts
> chore: change names

- packages/eslint-config-pluv/base.js
- packages/eslint-config-pluv/react.js
- packages/react/package.json
> fix(react): fix linting

- .changeset/light-paths-clap.md
- packages/react/src/createBundle.tsx
- tests/e2e/src/pages/yjs/cloudflare/presence/index.tsx
- tests/e2e/src/pages/yjs/cloudflare/storage/index.tsx
- tests/e2e/src/pluv-io/yjs/cloudflare.ts
---
Fix `PluvRoomProvider` never connecting when `metadata` is a function.
> fix(react): fix provider function metadata

- .changeset/tired-comics-divide.md
- packages/platform-cloudflare/package.json
- packages/platform-cloudflare/src/createPluvHandler.ts
- packages/platform-cloudflare/tsup.config.ts
---
Extend durable object instead of implements.
> feat(platform-cloudflare): extend durable object

- .changeset/slow-windows-shop.md
- packages/platform-cloudflare/src/createPluvHandler.ts
---
Fix return type for `createPluvHandler`.
> fix(platform-cloudflare): fix return type for createPluvHandler

- packages/types/src/pluv.ts
---
Added support for zod@^4 (currently in beta, so this might break eventually).
> feat(types): support zod v4

- .github/workflows/e2e-tests.yml
- .github/workflows/type-tests.yml
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- tests/e2e/package.json
- tests/types/eslint.config.mjs
- tests/types/package.json
- tests/types/src/types.test.ts
- tests/types/tsconfig.json
> test: added type tests

- packages/addon-indexeddb/package.json
- packages/cli/package.json
- packages/cli/src/utils/buildApp/resolveDependencies.ts
- packages/client/package.json
- packages/client/src/MockedRoom.ts
- packages/client/src/PluvRoom.ts
- packages/crdt-loro/package.json
- packages/crdt-loro/src/list.ts
- packages/crdt-loro/src/map.ts
- packages/crdt-loro/src/movableList.ts
- packages/crdt-loro/src/object.ts
- packages/crdt-yjs/package.json
- packages/crdt/package.json
- packages/io/package.json
- packages/persistence-cloudflare-transactional-storage/package.json
- packages/persistence-redis/package.json
- packages/platform-cloudflare/package.json
- packages/platform-node/package.json
- packages/platform-pluv/package.json
- packages/pubsub-redis/package.json
- packages/react/package.json
- packages/types/package.json
- tests/e2e/package.json
- tests/e2e/src/pluv-io/loro/node.ts
> fix: fix linting

- .changeset/proud-hoops-rule.md
- packages/io/src/IORoom.ts
- packages/io/src/index.ts
- packages/io/src/utils/getUserConnectionId.ts
- packages/io/src/utils/index.ts
- packages/platform-cloudflare/src/CloudflareWebSocket.ts
- packages/platform-node/src/NodeWebSocket.ts
---
Updated connection id to be deterministic based on the authorized user's id.
> feat(io): deterministic authorized session

- packages/io/src/IORoom.ts
- packages/platform-cloudflare/src/CloudflareWebSocket.ts
---
Fix setting a deterministic connection id from the user's id.
> fix(io): fix setting deterministic connection id from user id

- packages/platform-cloudflare/src/CloudflareWebSocket.ts
- packages/platform-node/src/NodeWebSocket.ts
---
Revert deterministic session id.
> revert(io): revert deterministic session id

- .changeset/fresh-ideas-listen.md
- packages/client/src/UsersManager.ts
- packages/client/src/constants.ts
> feat(client): limit presence max size

- .changeset/many-poets-carry.md
- packages/io/src/IORoom.ts
- packages/io/src/constants.ts
- packages/io/src/types.ts
---
Added garbage collection to clear dead websockets.
> fix(io): clear stale connections

- .changeset/better-bats-press.md
- .changeset/many-poets-carry.md
- packages/platform-cloudflare/src/constants.ts
- packages/platform-cloudflare/src/createPluvHandler.ts
---
Handle the garbage collection logic in `createPluvHandler`.
> feat(platform-cloudflare): handle garbage collection

- .changeset/honest-chefs-wear.md
- packages/platform-cloudflare/src/platformCloudflare.ts
- tests/types/src/types.test.ts
---
Fix inferred context type.
> fix(platform-cloudflare): fix context type

- .changeset/calm-dots-battle.md
- packages/platform-node/src/platformNode.ts
---
Fix inferred context type.
> fix(platform-node): fix context type

- .changeset/curvy-bats-sing.md
- packages/client/src/PluvRoom.ts
- packages/client/src/UsersManager.ts
---
Automatically add missing user on presence updates.
> feat(client): auto add missing user on presence

- packages/io/src/PluvServer.ts
- packages/types/src/index.ts
- packages/types/src/pluv.ts
---
Simplify event types (flattened an internal type).
> refactor(types): simplify event types

- .changeset/beige-carrots-fold.md
- packages/client/src/PluvRoom.ts
- packages/client/src/UsersManager.ts
- packages/client/src/utils/index.ts
- packages/client/src/utils/pickBy.ts
- packages/io/src/PluvServer.ts
- packages/io/src/utils/index.ts
- packages/io/src/utils/pickBy.ts
---
Fix presence becoming partial and failing presence schema validation.
> fix: fix presence validation

- .changeset/nine-suns-glow.md
- packages/client/src/PluvRoom.ts
---
Fix error being thrown about missing wsEndpoint when a public key is provided.
> fix(client): fix ws endpoint error

- .changeset/easy-emus-wear.md
- packages/platform-pluv/src/PluvPlatform.ts
---
Allow hidden endpoints parameter to be provided as a function.
> feat(platform-pluv): allow function endpoints

- .changeset/empty-rivers-yell.md
- packages/io/src/PluvServer.ts
- packages/io/src/constants.ts
---
Added configurable max storage size limit.
> feat(io): max storage size limit

- .changeset/empty-rivers-yell.md
- .changeset/true-walls-relate.md
- packages/io/src/PluvIO.ts
- packages/io/src/PluvServer.ts
- packages/io/src/constants.ts
- packages/io/src/types.ts
---
Added more configurable limits, and set a default max length for user id lengths.
> feat(io): more configurable limits

- .changeset/wide-tables-mix.md
- packages/client/src/MockedRoom.ts
- packages/client/src/PluvClient.ts
- packages/client/src/PluvRoom.ts
- packages/client/src/UsersManager.ts
- packages/client/src/types.ts
---
Added configurable limits for client-side validation. These should only be updated if you control the server and the server limits have been changed.
> feat(client): client limits

- .changeset/chilly-pots-turn.md
- .changeset/true-walls-relate.md
- packages/io/src/createIO.ts
- packages/io/src/index.ts
- packages/platform-cloudflare/src/platformCloudflare.ts
- packages/platform-node/src/platformNode.ts
- packages/platform-pluv/src/platformPluv.ts
---
Update `platformNode` and `platformCloudflare` to be able to configure limits for `PluvIO` (when self-hosted).
> feat: update platformNode and platformCloudflare with limits

- .changeset/poor-ravens-create.md
- packages/client/src/PluvRoom.ts
---
Fix potential edge case where event handlers may be called redundantly.
> fix(client): prevent redundant listeners

- .changeset/shaggy-birds-lick.md
- packages/client/src/PluvRoom.ts
---
Fix `PluvRoom` not properly reconnecting when connections are unavailable.
> fix(client): fix broken reconnects

- .changeset/long-spiders-cough.md
- packages/client/src/CrdtManager.ts
- packages/crdt-loro/src/doc/CrdtLoroDoc.ts
- packages/crdt-yjs/src/doc/CrdtYjsDoc.ts
- packages/crdt/src/AbstractCrdtDoc.ts
- packages/crdt/src/NoopCrdtDoc.ts
- packages/crdt/src/index.ts
- packages/io/src/PluvServer.ts
---
Updated `batchApplyEncodedState` to use `Yjs.mergeUpdates` to more efficiently update the document under-the-hood, while also producing a smaller document.
> feat(crdt): efficient batch update

- .changeset/spicy-squids-worry.md
- packages/client/src/PluvRoom.ts
---
Update `PluvRoom` to attempt to reconnect if currently disconnected when the window is re-focused.
> feat(client): window focus reconnect

- pnpm-lock.yaml
- tests/e2e/package.json
- tests/e2e/src/server/yjs/node/index.ts
---
Update Node.js tests to no-longer use deprecated `createPluvHandler`.
> tests(e2e): update nodejs tests

- .changeset/pretty-radios-smile.md
- packages/react/package.json
- pnpm-lock.yaml
---
`@pluv/client` is now a peer dependency of `@pluv/react`.
> feat(react): client peer dep

- .changeset/sharp-humans-cheer.md
> feat: v1 stable release

- pnpm-lock.yaml
- tests/e2e/package.json
- tests/e2e/src/components/yjs/cloudflare/SlateEditor.tsx
- tests/e2e/src/components/yjs/cloudflare/index.ts
- tests/e2e/src/components/yjs/node-redis/SlateEditor.tsx
- tests/e2e/src/components/yjs/node-redis/index.ts
- tests/e2e/src/components/yjs/node/SlateEditor.tsx
- tests/e2e/src/components/yjs/node/index.ts
- tests/e2e/src/pages/yjs/cloudflare/index.tsx
- tests/e2e/src/pages/yjs/cloudflare/slate/index.tsx
- tests/e2e/src/pages/yjs/node-redis/index.tsx
- tests/e2e/src/pages/yjs/node-redis/slate/index.tsx
- tests/e2e/src/pages/yjs/node/index.tsx
- tests/e2e/src/pages/yjs/node/slate/index.tsx
- tests/e2e/src/pluv-io/yjs/cloudflare.ts
- tests/e2e/src/pluv-io/yjs/node-redis.ts
- tests/e2e/src/pluv-io/yjs/node.ts
- tests/e2e/src/tests/yjs/cloudflare-kv/slate/index.test.ts
- tests/e2e/src/tests/yjs/cloudflare-sqlite/slate/index.test.ts
- tests/e2e/src/tests/yjs/node-redis/slate/index.test.ts
- tests/e2e/src/tests/yjs/node/slate/index.test.ts
> tests: added slate tests

- tests/e2e/src/tests/yjs/cloudflare-kv/slate/index.test.ts
- tests/e2e/src/tests/yjs/cloudflare-sqlite/slate/index.test.ts
- tests/e2e/src/tests/yjs/node-redis/slate/index.test.ts
- tests/e2e/src/tests/yjs/node/slate/index.test.ts
> tests: fix names

- .changeset/nine-mirrors-pick.md
- packages/client/src/CrdtManager.ts
- packages/client/src/PluvRoom.ts
- packages/crdt-yjs/src/doc/CrdtYjsDocFactory.ts
- packages/crdt/src/AbstractCrdtDocFactory.ts
- packages/io/src/IORoom.ts
- packages/io/src/PluvServer.ts
- packages/types/src/pluv.ts
---
Restore indexeddb addon capability.
> feat: restore indexeddb addon

- tests/e2e/src/tests/loro/node/presence/index.test.ts
- tests/e2e/src/tests/loro/node/storage/index.test.ts
- tests/e2e/src/tests/noop/node/presence/index.test.ts
- tests/e2e/src/tests/yjs/cloudflare-kv/presence/index.test.ts
- tests/e2e/src/tests/yjs/cloudflare-kv/slate/index.test.ts
- tests/e2e/src/tests/yjs/cloudflare-kv/storage/index.test.ts
- tests/e2e/src/tests/yjs/cloudflare-sqlite/presence/index.test.ts
- tests/e2e/src/tests/yjs/cloudflare-sqlite/slate/index.test.ts
- tests/e2e/src/tests/yjs/cloudflare-sqlite/storage/index.test.ts
- tests/e2e/src/tests/yjs/node-redis/presence/index.test.ts
- tests/e2e/src/tests/yjs/node-redis/slate/index.test.ts
- tests/e2e/src/tests/yjs/node-redis/storage/index.test.ts
- tests/e2e/src/tests/yjs/node/broadcast/index.test.ts
- tests/e2e/src/tests/yjs/node/presence/index.test.ts
- tests/e2e/src/tests/yjs/node/slate/index.test.ts
- tests/e2e/src/tests/yjs/node/storage/index.test.ts
> tests: increase waits from 0.25ms to 0.25s

- .changeset/modern-adults-allow.md
- packages/client/src/MockedRoom.ts
- packages/client/src/PluvRoom.ts
- tests/e2e/src/tests/yjs/node/storage/index.test.ts
---
Fix storage store failing initialization because id is undefined during the addon's initialization.
> fix(client): fix storage store initialization

- .changeset/blue-parents-dream.md
- packages/client/src/index.ts
---
Fixed `ConnectionState` not being exported.
> fix(client): fix non exported connection state

- .changeset/honest-lizards-brake.md
- packages/crdt-loro/src/doc/CrdtLoroDoc.ts
- packages/crdt-yjs/src/doc/CrdtYjsDoc.ts
- packages/crdt-yjs/src/object/object.ts
---
Updated deprecation warnings.
> feat: update deprecation warning

- .changeset/tricky-humans-run.md
- packages/client/src/PluvRoom.ts
- packages/client/src/UsersManager.ts
- packages/client/src/constants.ts
- packages/crdt-yjs/package.json
- packages/crdt-yjs/src/awareness/PluvYjsAwareness.ts
- packages/crdt-yjs/src/awareness/awareness.ts
- packages/crdt-yjs/src/awareness/index.ts
- packages/crdt-yjs/src/constants.ts
- packages/crdt-yjs/src/types.ts
- packages/crdt-yjs/src/yjs.ts
- pnpm-lock.yaml
> feat(crdt-yjs): awareness

- .changeset/fifty-dingos-speak.md
- packages/cli/package.json
- packages/crdt-loro/package.json
- packages/crdt-yjs/package.json
- packages/crdt-yjs/src/provider/PluvYjsProvider.ts
- packages/crdt-yjs/src/provider/index.ts
- packages/crdt-yjs/src/provider/provider.ts
- packages/crdt-yjs/src/types.ts
- packages/crdt-yjs/src/yjs.ts
- packages/persistence-cloudflare-transactional-storage/package.json
- packages/persistence-redis/package.json
- packages/platform-cloudflare/package.json
- packages/platform-node/package.json
- packages/platform-pluv/package.json
- packages/pubsub-redis/package.json
- pnpm-lock.yaml
- tests/e2e/package.json
- tests/types/package.json
---
Added a `provider` function that satisfies Yjs's provider interface.
> feat(crdt-yjs): provider

- packages/crdt-yjs/src/awareness/PluvYjsAwareness.ts
- packages/crdt-yjs/src/awareness/awareness.ts
- packages/crdt-yjs/src/constants.ts
- packages/crdt-yjs/src/provider/PluvYjsProvider.ts
- packages/crdt-yjs/src/provider/provider.ts
- packages/types/src/index.ts
---
Updated awareness presence to use pluv presence.
> feat(crdt-yjs): updated awareness presence to use pluv presence

- packages/crdt-yjs/src/awareness/PluvYjsAwareness.ts
- packages/crdt-yjs/src/awareness/awareness.ts
- packages/crdt-yjs/src/provider/PluvYjsProvider.ts
- packages/crdt-yjs/src/provider/provider.ts
- packages/react/src/createBundle.tsx
- pnpm-lock.yaml
- tests/e2e/package.json
- tests/e2e/src/components/yjs/cloudflare/LexicalEditor/Editor.tsx
- tests/e2e/src/components/yjs/cloudflare/LexicalEditor/ExampleTheme.ts
- tests/e2e/src/components/yjs/cloudflare/LexicalEditor/LexicalEditor.tsx
- tests/e2e/src/components/yjs/cloudflare/LexicalEditor/getRandomUserProfile.ts
- tests/e2e/src/components/yjs/cloudflare/LexicalEditor/index.ts
- tests/e2e/src/components/yjs/cloudflare/LexicalEditor/plugins/ToolbarPlugin.tsx
- tests/e2e/src/components/yjs/cloudflare/LexicalEditor/plugins/TreeViewPlugin.tsx
- tests/e2e/src/components/yjs/cloudflare/index.ts
- tests/e2e/src/pages/_app.tsx
- tests/e2e/src/pages/yjs/cloudflare/index.tsx
- tests/e2e/src/pages/yjs/cloudflare/lexical/index.tsx
- tests/e2e/src/pluv-io/yjs/cloudflare.ts
- tests/e2e/src/pluv-io/yjs/node-redis.ts
- tests/e2e/src/pluv-io/yjs/node.ts
- tests/e2e/src/styles/styles.css
- tests/e2e/src/tests/yjs/cloudflare-sqlite/lexical/index.test.ts
---
* Added yjs-lexical tests.
* Fixed various type inferrences.
> tests: added yjs lexical tests

- .changeset/solid-wasps-beg.md
- packages/client/src/types.ts
- packages/react/src/createBundle.tsx
- packages/react/src/index.ts
- packages/react/src/types.ts
> feat(react): infer bundle room

- pnpm-lock.yaml
- tests/e2e/package.json
- tests/e2e/src/components/yjs/cloudflare/BlockNoteEditor/BlockNoteEditor.tsx
- tests/e2e/src/components/yjs/cloudflare/BlockNoteEditor/BlockNoteEditorInner.tsx
- tests/e2e/src/components/yjs/cloudflare/BlockNoteEditor/BlockNoteEditorProvider.tsx
- tests/e2e/src/components/yjs/cloudflare/BlockNoteEditor/context.ts
- tests/e2e/src/components/yjs/cloudflare/BlockNoteEditor/getRandomUserProfile.ts
- tests/e2e/src/components/yjs/cloudflare/BlockNoteEditor/index.ts
- tests/e2e/src/components/yjs/cloudflare/LexicalEditor/LexicalEditor.tsx
- tests/e2e/src/components/yjs/cloudflare/index.ts
- tests/e2e/src/pages/_app.tsx
- tests/e2e/src/pages/yjs/cloudflare/blocknote/index.tsx
- tests/e2e/src/pluv-io/yjs/cloudflare.ts
- tests/e2e/src/tests/yjs/cloudflare-sqlite/blocknote/index.test.ts
> tests: added blocknote tests

- .changeset/rude-ties-rule.md
- .changeset/slow-boats-wash.md
- docs/migration-guides/v3.mdx
- packages/client/src/MockedRoom.ts
- packages/client/src/PluvRoom.ts
- packages/react/src/createBundle.tsx
- packages/react/src/types.ts
- packages/types/src/pluv/room.ts
- tests/e2e/src/components/yjs/cloudflare/BlockNoteEditor/BlockNoteEditorProvider.tsx
- tests/e2e/src/components/yjs/cloudflare/LexicalEditor/LexicalEditor.tsx
- tests/types/src/types.test.tsx
---
Fix doc being available before storage was initialized.
> fix: fix preemptive doc

- .changeset/puny-lands-open.md
- packages/react/src/types.ts
---
Fixed `useConnection` requiring a selector function (this is now optional).
> fix: fix use connection types

- .changeset/light-berries-burn.md
- .changeset/mean-eagles-mix.md
- docker-compose.yml
- packages/io/src/IORoom.ts
- packages/io/src/PluvIO.ts
- packages/io/src/PluvServer.ts
- packages/io/src/createIO.ts
- packages/io/src/types.ts
- packages/platform-cloudflare/src/platformCloudflare.ts
- packages/platform-node/src/platformNode.ts
- packages/platform-pluv/src/PluvPlatform.ts
- packages/platform-pluv/src/platformPluv.ts
- packages/platform-pluv/src/types.ts
- packages/react/src/createBundle.tsx
- tests/e2e/src/pages/yjs/cloudflare/presence/index.tsx
- tests/e2e/src/pages/yjs/cloudflare/storage/index.tsx
- tests/e2e/src/tests/yjs/cloudflare-sqlite/presence/index.test.ts
---
Fix error that would occur when a user changes rooms on Cloudflare, where method references would be shared between Cloudflare Durable Objects.
> fix(io): fix change room

- .changeset/rude-ties-rule.md
- .changeset/slow-boats-wash.md
- packages/client/src/CrdtManager.ts
- packages/client/src/MockedRoom.ts
- packages/client/src/PluvRoom.ts
- packages/react/src/types.ts
- packages/types/src/pluv/room.ts
- tests/e2e/src/components/yjs/cloudflare/BlockNoteEditor/BlockNoteEditorInner.tsx
- tests/e2e/src/components/yjs/cloudflare/BlockNoteEditor/BlockNoteEditorProvider.tsx
- tests/e2e/src/components/yjs/cloudflare/LexicalEditor/LexicalEditor.tsx
- tests/types/src/types.test.tsx
---
Updated `PluvRoom` to have a stable doc per new connection.
> feat(client): updated PluvRoom to have a stable doc per new connection

- .changeset/five-cobras-film.md
- packages/io/src/AbstractPlatform.ts
- packages/io/src/PluvIO.ts
- packages/io/src/PluvServer.ts
- packages/platform-pluv/src/PluvPlatform.ts
---
Fix `createToken` throwing a TypeError.
> fix(platform-pluv): fix create token

- .changeset/lovely-ears-post.md
- packages/crdt-yjs/src/awareness/PluvYjsAwareness.ts
- packages/crdt-yjs/src/provider/PluvYjsProvider.ts
- tests/e2e/src/components/yjs/cloudflare/BlockNoteEditor/BlockNoteEditorInner.tsx
- tests/e2e/src/components/yjs/cloudflare/LexicalEditor/LexicalEditor.tsx
---
Updated `yjs.provider` field to `presenceField`.
> feat(crdt-yjs): updated provider field to presenceField

- .changeset/better-states-relate.md
- packages/platform-pluv/src/PluvPlatform.ts
> feat(platform-pluv): add more debug logging

- .changeset/tough-waves-stare.md
- packages/io/src/AbstractPersistence.ts
- packages/io/src/AbstractPlatform.ts
- packages/persistence-cloudflare-transactional-storage/src/PersistenceCloudflareTransactionalStorage.ts
- packages/persistence-redis/src/PersistenceRedis.ts
- packages/platform-cloudflare/src/CloudflarePlatform.ts
---
Fixed storage state not being written into transactional storage.
> fix(platform-cloudflare): fix storage state write

- .changeset/sour-maps-press.md
- packages/platform-pluv/src/PluvPlatform.ts
---
Fixed the context in `platformPluv` being declared immediately, instead of when the event listeners ran (causing errors in Cloudflare Workers).
> fix(platform-pluv): fix context derivation

- .changeset/orange-ghosts-joke.md
- packages/io/src/PluvServer.ts
---
Fixed `ioServer.fetch` not receiving the `PluvServer` config.
> fix(platform-pluv): fix fetch config

- .changeset/fresh-grapes-stop.md
- packages/io/src/PluvServer.ts
- packages/platform-pluv/src/PluvPlatform.ts
---
Added webhook debug logging.
> feat(platform-pluv): added webhook logging

- packages/addon-indexeddb/src/addonIndexedDB.ts
- packages/client/src/PluvClient.ts
- packages/client/src/PluvRoom.ts
- packages/client/src/createClient.ts
- packages/client/src/infer.ts
- packages/crdt-yjs/src/awareness/PluvYjsAwareness.ts
- packages/crdt-yjs/src/awareness/awareness.ts
- packages/crdt-yjs/src/provider/PluvYjsProvider.ts
- packages/crdt-yjs/src/provider/provider.ts
- packages/io/src/IORoom.ts
- packages/io/src/PluvServer.ts
- packages/react/src/createBundle.tsx
- packages/react/src/types.ts
- packages/types/src/pluv/room.ts
- packages/types/src/pluv/shared.ts
> feat(io): add crdt type to IOLike

- .changeset/new-singers-drop.md
- packages/io/src/PluvServer.ts
---
Fixed applying empty getInitialStorage.
> fix(io): prevent apply empty state

- .changeset/cute-rivers-buy.md
- packages/client/src/PluvRoom.ts
- packages/crdt/src/AbstractCrdtDocFactory.ts
- tests/e2e/src/components/yjs/node/BlockNoteEditor/BlockNoteEditor.tsx
- tests/e2e/src/components/yjs/node/BlockNoteEditor/BlockNoteEditorInner.tsx
- tests/e2e/src/components/yjs/node/BlockNoteEditor/BlockNoteEditorProvider.tsx
- tests/e2e/src/components/yjs/node/BlockNoteEditor/context.ts
- tests/e2e/src/components/yjs/node/BlockNoteEditor/getRandomUserProfile.ts
- tests/e2e/src/components/yjs/node/BlockNoteEditor/index.ts
- tests/e2e/src/components/yjs/node/index.ts
- tests/e2e/src/pages/yjs/node/blocknote/index.tsx
- tests/e2e/src/pluv-io/yjs/node.ts
---
Fixed empty initial storage case.
> fix(client): prevent apply empty store

- .changeset/stale-tips-mate.md
- packages/crdt-loro/src/doc/CrdtLoroDoc.ts
- packages/crdt-yjs/src/doc/CrdtYjsDoc.ts
- packages/react/src/createBundle.tsx
---
Fixed CRDT docs being considered as `empty` even when there are properties (i.e. yjs shared types and loro container types) on the document when they have not been modified.
> fix(crdt): fix empty doc

- .changeset/sharp-hands-relax.md
- packages/react/src/createBundle.tsx
> fix(react): fix excessive rerenders

- packages/crdt/src/AbstractCrdtDocFactory.ts
- packages/io/src/IORoom.ts
- packages/io/src/PluvServer.ts
- packages/types/src/pluv/crdt.ts
> refactor: is empty checks

- .changeset/full-eggs-study.md
- packages/client/src/MockedRoom.ts
- packages/client/src/PluvRoom.ts
- packages/crdt-loro/src/doc/CrdtLoroDoc.ts
- packages/crdt-yjs/src/doc/CrdtYjsDoc.ts
- pnpm-lock.yaml
- tests/e2e/package.json
---
Updated crdt internal private properties to use native [private elements](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_elements).
> feat: update private access modifiers

- packages/platform-pluv/package.json
- pnpm-lock.yaml
- tests/e2e/package.json
- tests/types/package.json
- tests/types/src/types.test.tsx
> chore: bump zod v4
