pluv-io/pluv

.changeset/clever-pets-marry.md, .changeset/neat-dodos-jump.md, packages/client/src/CrdtManager.ts, packages/client/src/PluvRoom.ts, packages/io/src/IORoom.ts, packages/io/src/PluvIO.ts, packages/io/src/createIO.ts
---
* Added support for setting the initial storage state of the IORoom from external storage sources (e.g. databases).
=> feat(io): support for setting the initial storage from external source

.github/auto-assign.yml
---
Exclude renovate from auto-assign workflow.
=> ci: exclude renovate in auto-assign workflow

.github/auto-assign.yml, renovate.json
---
Updated renovate and auto-assign so that renovate bot isn't auto-assigned in pull requests.
=> chore: update renovate to not be auto-assigned in pull requests

.changeset/hip-flies-float.md, docs/crdt-storage.md, packages/crdt-yjs/README.md, packages/crdt-yjs/src/doc.ts, packages/crdt-yjs/src/index.ts, packages/crdt-yjs/src/types.ts, packages/crdt-yjs/src/xmlElement.ts, packages/crdt-yjs/src/xmlFragment.ts, packages/crdt-yjs/src/xmlText.ts, packages/io/README.md
---
Added support for remaining yjs shared types: `y.xmlFragment`, `y.xmlElement` and `y.xmlText`.
=> chore(crdt-yjs): added support for remaining yjs shared types

internal/react-chess/src/ChessBoard.tsx, internal/react-chess/src/context.ts, internal/react-chess/src/customPieces.tsx, internal/react-chess/src/defaultPieces.tsx, internal/react-chess/src/getCustomPiece.tsx, internal/react-chess/src/index.ts, internal/react-chess/src/types.ts
---
Added decorator for chess pieces so that presence-related styles can be added eventually.
=> docs(web): added decorator for chess pieces

.github/workflows/auto-assign.yml
---
* Replaced auto assign GitHub action to self-assign PRs and issues.
=> ci: replaced auto-assign action

.changeset/eleven-apricots-trade.md, .changeset/five-maps-dance.md, apps/web/src/components/DocsBreadcrumbs/DocsBreadcrumbs.tsx, apps/web/src/components/DocsTreeViewNavigation/DocsTreeViewNavigationRoutes.tsx, packages/client/src/PluvClient.ts
---
* Changed `PluvClient.enter` to return the `PluvRoom` that was entered.
* Changed `PluvClient.createRoom` to have optional options.
=> feat: return room from PluvClient.createRoom

.changeset/ninety-dogs-live.md, packages/client/src/MockedRoom.ts, packages/react/src/createBundle.tsx
---
Fixed MockedRoom events always requiring all events to be mocked.
=> fix: changed MockedRoom events to accept partial event mocks

.changeset/silent-wasps-sing.md, packages/react/src/createRoomBundle.tsx
---
Updated @pluv/react to prevent rerendering if state values are deeply equal by default.
=> feat: prevent rerender on deep equal

.changeset/slow-pears-mix.md, packages/client/src/PluvRoom.ts, packages/client/src/UsersManager.ts, packages/io/src/IORoom.ts, packages/io/src/PluvIO.ts, packages/types/src/pluv.ts
---
Updated `$USER_JOINED` event to use the user's current presence if they had one previously (for example if they lost network connection, and updated their presence).
=> feat: use existing presence of reconnected user

packages/platform-node/src/createPluvHandler.ts, tests/e2e/src/server/node/index.ts
---
Returned `createWsServer`, `handler` and `wsHandler` from @pluv/platform-node createPluvHandler to allow the handlers to be extended.
=> feat: return more extensible parts from node createPluvHandler

.changeset/quiet-flies-burn.md, packages/io/src/PluvIO.ts, packages/io/src/createIO.ts, packages/io/src/index.ts, tests/e2e/src/server/node/pluv-io.ts
---
Updated `initialStorage` to be renamed to `getInitialStorage`. Changed parameters to use a parameterized object that includes the platform context and the room name.
=> feat: new io initial storage

.changeset/tame-ants-clap.md, packages/client/src/y.ts, packages/crdt-yjs/src/index.ts, packages/crdt-yjs/src/object.ts, packages/crdt-yjs/src/types.ts
---
* Renamed type `unstable_YObjectValue` to `YObjectValue`;
* Renamed type `unstable_YObject` to `YObject`.
* Re-exported `xmlElement`, `xmlFragment` and `xmlText` from `@pluv/client`.
```ts
import { y } from "@pluv/client"
// or
import { y } from "@pluv/react";
y.xmlElement("MyElement", {});
y.xmlFragment({});
y.xmlText("hello world");
```
=> feat: expose xml yjs types

.changeset/lemon-eels-clap.md, packages/io/src/PluvIO.ts
---
Expose io context and getInitialStorage.
=> feat(io): expose io context and get initial storage

apps/web/src/inputs/docs/@pluv_client/API Reference.mdx, apps/web/src/inputs/docs/@pluv_react/API Reference.mdx, packages/client/src/AbstractRoom.ts, packages/client/src/MockedRoom.ts, packages/client/src/PluvRoom.ts, packages/react/src/createRoomBundle.tsx
---
Updated storage from `getStorage` to never return null.
=> feat(client): update storage to never be null

.changeset/soft-boxes-poke.md, packages/client/src/PluvRoom.ts
---
Added `getDoc` to `PluvRoom` to be able to access the root Yjs document.
=> feat(client): expose the root yjs doc from room

.changeset/mighty-maps-lie.md, packages/client/src/AbstractRoom.ts, packages/client/src/MockedRoom.ts, packages/react/src/createRoomBundle.tsx
---
Added `usePluvDoc` to access the root yjs doc.
=> feat(react): added usePluvDoc to access the root yjs doc

.changeset/cold-rockets-trade.md, packages/io/src/PluvIO.ts, packages/io/src/index.ts
---
Moved exposed installed version of `@pluv/io` to the `PluvIO` instance.
=> feat(io): move version to pluv io

.changeset/lucky-humans-help.md, packages/io/src/AbstractWebSocket.ts, packages/io/src/IORoom.ts, packages/io/src/PluvIO.ts, packages/io/src/types.ts
---
Narrow the type of `user` on `WebsocketSession` in `@pluv/io`.
=> feat(io): narrow type of user on io session

.changeset/smooth-kings-swim.md, packages/client/src/PluvRoom.ts, tests/e2e/src/server/yjs/node/pluv-io.ts
=> feat(client): event proxy

.changeset/moody-ties-double.md, packages/react/package.json, packages/react/src/createRoomBundle.tsx, pnpm-lock.yaml
---
`useOthers` has been updated to allow returning non-array values when using a custom selector.
=> feat(react): update use others return type

apps/server-cloudflare/src/index.ts, packages/io/src/AbstractWebSocket.ts, packages/io/src/IORoom.ts, packages/platform-cloudflare/src/CloudflareWebSocket.ts, packages/platform-node/src/NodePlatform.ts, packages/platform-node/src/NodeWebSocket.ts
---
Move session id to AbstractWebsocket from IORoom.
=> feat(io): move sessionId to websocket instead of IORoom

.changeset/blue-lobsters-argue.md, packages/io/src/AbstractPlatform.ts, packages/platform-cloudflare/src/CloudflarePlatform.ts, packages/platform-cloudflare/src/constants.ts, packages/platform-cloudflare/src/platformCloudflare.ts, packages/platform-node/src/NodePlatform.ts, packages/platform-node/src/index.ts, packages/platform-node/src/platformNode.ts
Closes #670
---
* Support Cloudflare Worker WebSocket Hibernation API.
* Default `@pluv/platform-cloudflare` to use detached mode (i.e. use websocket hibernation by default).
=> feat(platform-cloudflare): support websocket hibernation

.changeset/chatty-grapes-hug.md, packages/io/src/IORoom.ts, packages/io/src/PluvIO.ts, packages/io/src/PluvRouter.ts, packages/io/src/PluvServer.ts, packages/io/src/createIO.ts, packages/io/src/types.ts, packages/types/src/index.ts, packages/types/src/pluv.ts, tests/e2e/src/server/yjs/node/pluv-io.ts
---
Updated `onRoomDeleted` and `onStorageUpdated` to be configured on `io.server` instead of on `createIO`.
=> feat(io): update event listeners to be configured on the server

.changeset/beige-seas-beg.md, packages/client/src/OtherNotifier.ts, packages/client/src/PluvRoom.ts, packages/client/src/UsersManager.ts
---
When the websocket connection is closed, clear stateful information for others and the user.
=> fix(client): clear users on ws close

.changeset/early-seas-live.md, packages/io/src/AbstractPlatform.ts, packages/io/src/IORoom.ts
---
Fix `IORoom` `onRoomMessage` event being triggered on message sent instead of message received.
=> fix(io): fix message event on recieve

.changeset/tasty-moles-play.md, packages/client/src/PluvClient.ts, packages/react/src/createRoomBundle.tsx
---
Remove `createRoomBundle`'s `initialStorage` prop.
=> feat(react): remove room bundle initial storage

.changeset/fast-monkeys-admire.md, packages/crdt-loro/src/loro.ts, packages/crdt-yjs/src/yjs.ts, packages/io/src/PluvIO.ts, packages/io/src/PluvServer.ts, packages/io/src/createIO.ts, packages/io/src/index.ts, packages/io/src/types.ts
---
Added `CrdtLibraryType`. Updated `@pluv/crdt-yjs` and `@pluv/crdt-loro` to expose a property `kind` that identifies the crdt type.
=> refactor(io): add crdt-library-type

.changeset/twelve-lies-tickle.md, packages/io/src/IORoom.ts, packages/io/src/PluvServer.ts, packages/io/src/index.ts, packages/io/src/types.ts
---
Expose websocket on `onRoomMessage` and `onStorageUpdated` events.
=> feat(io): expose websocket on events

.changeset/cyan-jeans-tap.md, apps/web/src/inputs/docs/@pluv_io/Cloudflare Workers.mdx, packages/io/src/PluvIO.ts, packages/io/src/PluvServer.ts, packages/io/src/types.ts, packages/platform-pluv/src/PluvIO.ts
---
Get initial storage context.
=> feat(io): get initial storage context

.changeset/light-crews-invite.md, packages/crdt-loro/src/doc/CrdtLoroDoc.ts
---
Update internal, deprecated loro-crdt methods.
=> chore(crdt loro): update deprecated methods

.changeset/quick-mirrors-smell.md, packages/crdt-loro/src/doc/CrdtLoroDoc.ts, tests/e2e/src/tests/loro/node/storage/index.test.ts, tests/e2e/src/tests/yjs/node/storage/index.test.ts
=> feat(crdt loro): undo redo

.changeset/eight-parents-cheer.md, packages/react/src/index.ts
---
Remove re-exports of `@pluv/client` and `@pluv/crdt` parts from `@pluv/react`.
=> feat(react): remove re-exports of client and crdt from react

.changeset/chatty-ears-run.md, packages/client/src/PluvRoom.ts
---
Update the default `wsEndpoint` when `publicKey` is provided.
=> feat(client): update default ws endpoint

.changeset/cold-sites-shout.md, packages/react/src/createBundle.tsx
---
Added error message about missing room if `PluvRoomProvider` was not used.
=> feat(react): add missing room error message

.changeset/itchy-ads-type.md, packages/platform-cloudflare/src/CloudflarePlatform.ts
---
Fix sending incorrect heartbeat event auto-responses for Cloudflare's WebSocket hibernation.
=> fix(platform cloudflare): fix auto ws response

.changeset/violet-files-scream.md, packages/io/src/PluvRouter.ts
---
Require `PluvRouter` event names to be formatted as valid JavaScript variable names.
=> feat(io): valid event names

.changeset/proud-gifts-boil.md, packages/platform-pluv/src/PluvPlatform.ts
---
Fix `TypeError` on event handler invocations once again.
=> fix(platform-pluv): undefined event call again

.changeset/fast-seals-build.md, packages/client/src/PluvRoom.ts
---
Update the user's presence locally only via `PluvRoom.updateMyPresence` (i.e. do not update the user's own presence from WebSocket messages) to avoid update delays. This should fix some cases of "jitter" depending on network latecy.
=> feat(client): local only presence updates

.changeset/odd-hotels-strive.md, packages/io/src/PluvIO.ts
---
Fix generic type default for router events on `PluvIO.server`.
=> fix(io): fix default router types

.changeset/bright-nights-read.md, .changeset/gold-areas-brake.md, .changeset/strong-banks-clean.md, .changeset/wet-planes-invent.md, .changeset/wicked-walls-attack.md, .changeset/wide-pandas-give.md, packages/client/src/PluvClient.ts, packages/client/src/PluvRoom.ts, packages/client/src/index.ts, packages/client/src/types.ts, packages/react/src/createBundle.tsx, packages/react/src/internal/hooks/index.ts, packages/react/src/internal/hooks/useAsyncQueue.ts, packages/react/src/internal/hooks/useDeepAsyncMemo.ts, packages/react/src/internal/index.ts
---
* `client`: Handle additional edge-cases for polling reconnects.
* `client`: Move metadata from `PluvClient.createRoom` to `PluvRoom.connect` (and in turn `PluvClient.enter`).
* `react`: Update `PluvRoomProvider` so that metadata usage internally is updated to how `PluvClient` now handles metadata (i.e. moving it to `PluvClient.enter`.
* `react`: Update `PluvRoomProvider` to have an additional optional `boolean` prop `connect` (default = `true`), which can be set to `false` to prevent connecting to the room until it is set to true.
* `react` Fix potential race conditions of entering and leaving the room during re-renders.
=> fix(client): improve connection handling

.changeset/tender-queens-lead.md, packages/client/src/MockedRoom.ts, packages/client/src/PluvClient.ts, packages/client/src/PluvRoom.ts, packages/client/src/types.ts
---
Added the ability to configure the reconnect timeout (in milliseconds) for a `PluvRoom`, and lowered the default reconnect timeout from 30s to 5s. Values will be automatically clamped to between 1s and 60s.
=> feat(client): reconnect timeout ms

.changeset/mighty-crabs-wink.md, packages/client/src/PluvClient.ts
---
Update the 2nd parameter of `PluvClient.createRoom` to be optional.
=> feat(client): optional create room options

.changeset/hungry-colts-unite.md, packages/client/src/PluvRoom.ts
---
Attempt to reconnect immediately after receiving a close event.
=> feat(client): attempt reconnect immediately after close

.changeset/clever-ghosts-say.md, packages/io/src/AbstractPlatform.ts, packages/io/src/AbstractWebSocket.ts, packages/io/src/IORoom.ts, packages/io/src/PluvServer.ts, packages/io/src/authorize.ts, packages/platform-cloudflare/src/CloudflarePlatform.ts, packages/platform-cloudflare/src/CloudflareWebSocket.ts, packages/platform-cloudflare/src/createPluvHandler.ts, packages/platform-cloudflare/src/platformCloudflare.ts, packages/platform-node/src/NodePlatform.ts, packages/platform-node/src/NodeWebSocket.ts, packages/platform-node/src/createPluvHandler.ts, packages/platform-node/src/platformNode.ts
---
Update how session users are stored on websockets.
=> feat(io): in-memory user on websocket

.changeset/salty-heads-clap.md, packages/io/src/IORoom.ts, packages/io/src/types.ts, packages/io/tsconfig.json, packages/platform-node/src/createPluvHandler.ts, packages/tsconfig/library.json
---
Fixed the return type of `createWsServer` from `createPluvHandler` to be `ws.WebSocketServer` instead of `ws.Server`.
=> fix(platform-node): fix ws server type

.changeset/bumpy-walls-stop.md, packages/io/src/PluvServer.ts, packages/io/src/constants.ts
---
Added a 512 byte limit to `user` provided to `PluvServer.createToken`.
=> feat(io): limit create token size to 512 bytes

.changeset/clever-ghosts-say.md, .changeset/empty-banks-judge.md, packages/io/src/PluvServer.ts, packages/io/src/constants.ts
---
Limit user's presence max size to 512 bytes.
=> feat(io): limit presence max size to 512 bytes

.changeset/pretty-pets-post.md, packages/platform-pluv/src/PluvPlatform.ts
---
Added the ability to use functions to return public keys, secret keys and webhook secrets for `@pluv/platform-pluv`.
=> feat(platform-pluv): lazy keys

.changeset/tiny-moles-worry.md, packages/io/src/IORoom.ts, packages/types/src/pluv.ts
---
Emit a sync-state of currently connected users when garbage collection is run.
=> feat(io): emit sync state when garbage collected

.changeset/khaki-spiders-cover.md, packages/io/src/AbstractPersistence.ts, packages/io/src/IORoom.ts, packages/io/src/Persistence.ts, packages/persistence-cloudflare-transactional-storage/src/PersistenceCloudflareTransactionalStorage.ts, packages/persistence-redis/src/PersistenceRedis.ts, packages/persistence-redis/src/utils/index.ts, packages/persistence-redis/src/utils/partitionByLength.ts, packages/types/src/pluv.ts
---
`Persistence.getUsers` now returns a map instead of an array.
=> feat: get users returns map

.changeset/big-tables-occur.md, packages/platform-cloudflare/src/createPluvHandler.ts, packages/platform-node/src/createPluvHandler.ts
---
Deprecated `createPluvHandler`.
=> chore: deprecate create pluv handler

.changeset/odd-cameras-care.md, packages/io/src/PluvIO.ts, packages/io/src/PluvServer.ts
---
Fixed not applying user size limits when calling `PluvIO.authorize` and not allowing it to be overwritten for `platformPluv`.
=> fix(io): fix io authorize override

.changeset/eager-rivers-obey.md, packages/io/src/PluvServer.ts
---
Fix 1 and 2 character long room names not being supported.
=> fix(io): allow smaller room names

.changeset/spicy-beds-happen.md, packages/client/src/enums.ts
---
The `ConnectionState` enum is now a `const` to avoid several pitfalls of using TypeScript enums.
=> feat(client): improve enum

.changeset/wicked-regions-roll.md, packages/client/src/PluvRoom.ts
---
Fix `PluvRoom._reconnect` not being called with the last used metadata (from `PluvRoom.connect`).
=> fix(client): fix reconnect metadata

.changeset/full-pants-kneel.md, packages/addon-indexeddb/src/addonIndexedDB.ts, packages/client/src/CrdtManager.ts, packages/client/src/MockedRoom.ts, packages/client/src/PluvClient.ts, packages/client/src/PluvRoom.ts, packages/client/src/createClient.ts, packages/crdt-loro/src/doc/CrdtLoroDocFactory.ts, packages/crdt-yjs/src/doc/CrdtYjsDocFactory.ts, packages/crdt/src/AbstractCrdtDocFactory.ts, packages/crdt/src/NoopCrdtDocFactory.ts, packages/crdt/src/index.ts, packages/crdt/src/types.ts, packages/react/src/createBundle.tsx, packages/types/src/pluv/crdt.ts, tests/types/package.json, tests/types/src/types.test.tsx, tests/types/tsconfig.json
---
Updated the `initialStorage` prop on `PluvRoomProvider` to now require using the builder type to declare type-level types. Deprecated using the crdt utilities to declare top-level types.
=> feat(react): initial storage builder

.changeset/some-dolls-yell.md, packages/client/src/PluvClient.ts
---
Fixed ignored `PluvClient.createRoom` `initialStorage` option.
=> fix(client): fix ignored create room initial storage

.changeset/lemon-sites-yawn.md, packages/client/src/CrdtNotifier.ts, packages/client/src/MockedRoom.ts, packages/client/src/PluvRoom.ts, packages/types/src/index.ts, packages/types/src/pluv/room.ts, tests/types/src/types.test.tsx
---
Updated `PluvRoom.storage` to also allow subscribing to storage fields as nested properties.
=> feat(client): storage proxy

.changeset/five-tables-brush.md, packages/client/src/PluvRoom.ts
---
**DEPRECATED** `PluvRoom.event`, `PluvRoom.storage`, `PluvRoom.storageRoot` and `PluvRoom.other` have all been deprecated, to be removed in v3. These now exist under `PluvRoom.subscribe` instead.
=> feat(client): deprecate several moved subscriptions

.changeset/rude-insects-sort.md, packages/client/src/MockedRoom.ts, packages/client/src/PluvRoom.ts, packages/client/src/index.ts, packages/client/src/types.ts, packages/crdt-yjs/src/awareness/PluvYjsAwareness.ts, packages/types/src/index.ts, packages/types/src/pluv/enums.ts, packages/types/src/pluv/room.ts
---
**DEPRECATED** `PluvRoom.storageLoaded` . Added `PluvRoom.getStorageLoaded` with improved detection of when the storage was synced.
=> feat(client): getStorageLoaded

.changeset/plenty-toes-dance.md, packages/client/src/ListenerManager.ts, packages/client/src/MockedRoom.ts, packages/client/src/PluvRoom.ts, packages/types/src/index.ts, packages/types/src/pluv/room.ts
---
Added the ability to listen to the room's underlying websocket's event listeners.
=> feat(client): ws event listeners

.changeset/pretty-mammals-sleep.md, packages/addon-indexeddb/src/addonIndexedDB.ts, packages/client/src/MockedRoom.ts, packages/client/src/PluvClient.ts, packages/client/src/PluvProcedure.ts, packages/client/src/PluvRoom.ts, packages/client/src/PluvRouter.ts, packages/client/src/StateNotifier.ts, packages/client/src/UsersManager.ts, packages/client/src/UsersNotifier.ts, packages/client/src/createClient.ts, packages/client/src/types.ts, packages/crdt-yjs/src/awareness/PluvYjsAwareness.ts, packages/crdt-yjs/src/awareness/awareness.ts, packages/crdt-yjs/src/provider/PluvYjsProvider.ts, packages/crdt-yjs/src/provider/provider.ts, packages/react/src/createBundle.tsx, packages/types/src/pluv/room.ts, tests/types/src/types.test.tsx
---
Updated `presence` types to be more lenient (i.e. no-longer extends `JsonObject`). This is to enable types like `.passthrough` with zod, which can be useful for integrating `yjs.awareness` with libraries such as [lexical](https://lexical.dev/).
=> feat(client): lenient presence type

.changeset/kind-geckos-punch.md, packages/crdt-yjs/src/awareness/PluvYjsAwareness.ts, packages/crdt-yjs/src/awareness/awareness.ts, packages/crdt-yjs/src/provider/PluvYjsProvider.ts, packages/crdt-yjs/src/provider/provider.ts, packages/crdt-yjs/src/types.ts, tests/e2e/src/components/yjs/cloudflare/LexicalEditor/LexicalEditor.tsx, tests/e2e/src/pluv-io/yjs/cloudflare.ts
---
Allow specifying Yjs awareness on a custom presence field.
=> feat(crdt-yjs): enable setting up awareness on a nested field

.changeset/fifty-dingos-speak.md, .changeset/kind-geckos-punch.md, .changeset/tricky-humans-run.md, packages/crdt-yjs/src/awareness/PluvYjsAwareness.ts, packages/crdt-yjs/src/awareness/awareness.ts, packages/crdt-yjs/src/provider/PluvYjsProvider.ts, tests/e2e/src/components/yjs/cloudflare/BlockNoteEditor/BlockNoteEditorInner.tsx, tests/e2e/src/components/yjs/cloudflare/BlockNoteEditor/BlockNoteEditorProvider.tsx, tests/e2e/src/components/yjs/cloudflare/BlockNoteEditor/context.ts, tests/e2e/src/components/yjs/cloudflare/LexicalEditor/LexicalEditor.tsx
---
No-longer require `doc` in `yjs.awareness` nor `yjs.provider`.
=> feat(crdt-yjs): no longer require doc

.changeset/five-cobras-fly.md, packages/crdt-loro/src/index.ts, packages/crdt-yjs/src/index.ts, packages/crdt/src/index.ts, packages/crdt/src/types.ts, packages/io/src/PluvIO.ts, packages/io/src/PluvServer.ts, packages/io/src/createIO.ts, packages/io/src/index.ts, packages/io/src/types.ts, packages/platform-cloudflare/package.json, packages/platform-cloudflare/src/platformCloudflare.ts, packages/platform-node/package.json, packages/platform-node/src/platformNode.ts, packages/platform-pluv/src/platformPluv.ts, pnpm-lock.yaml, tests/e2e/src/demo/io.ts, tests/e2e/src/server/loro/node/pluv-io.ts, tests/e2e/src/server/yjs/cloudflare/pluv-io/kv.ts, tests/e2e/src/server/yjs/cloudflare/pluv-io/sqlite.ts, tests/e2e/src/server/yjs/node-redis/pluv-io/first.ts, tests/e2e/src/server/yjs/node-redis/pluv-io/second.ts, tests/types/src/types.test.tsx
---
Fixed `getInitialStorage` not being required when `crdt` is provided.
=> fix(io): require get initial storage with crdt

.changeset/sad-coats-jam.md, packages/client/src/PluvClient.ts, packages/client/src/createClient.ts, packages/platform-cloudflare/src/platformCloudflare.ts, packages/platform-node/src/platformNode.ts, packages/platform-pluv/src/platformPluv.ts, packages/react/src/createBundle.tsx, packages/react/src/types.ts, packages/types/src/index.ts, packages/types/src/pluv/crdt.ts, packages/types/src/pluv/shared.ts, tests/e2e/src/pluv-io/loro/node.ts, tests/types/src/no-crdt.test.tsx, tests/types/src/types.test.tsx
---
Emit TypeScript error in `createClient` if `crdt` is incompatible on `createIO`.
=> feat(client): emit warning on missing crdt

.changeset/tasty-ghosts-smoke.md, packages/io/src/PluvIO.ts, packages/types/src/general.ts, packages/types/src/index.ts, tests/types/src/has-crdt.test.tsx
---
Fixed `PluvIO.server` not requiring input parameters (i.e. was optional) when `createIO` specified `crdt`.
=> fix(io): pluv server args
